### ISSUE TITLE
opinion

### ISSUE THREAD

**Issue by Ypsxc111** [The-Run-Philosophy-Organization/run#10]
想润，表示没钱

**Comment by Daniel-zb** [comment]
Run together! I believe we'll realize it in the future.

**Comment by JixiangSoong** [comment]
Any Wechat group? Wechat groups are necessary.

**Comment by tianyalang** [comment]
> Any Wechat group? Wechat groups are necessary.

but dangerous

**Comment by cultivater** [comment]
> > Any Wechat group? Wechat groups are necessary.
> 
> but dangerous

telegram is save

**Comment by cultivater** [comment]
> > Any Wechat group? Wechat groups are necessary.
> 
> but dangerous

telegram is safe

**Comment by the-run-philosophy** [comment]
已更新TELEGRAM和DISCORD

**Comment by the-run-philosophy** [comment]
参考主页README
