### ISSUE TITLE
「说润解字」-论润

### ISSUE THREAD

**Issue by Andrew1771-re** [The-Run-Philosophy-Organization/run#105]
润者，走也。普天之下，莫非王土。然王土虽大，亦有边界。王土之界，乃国门也。国门之外，大洋浩瀚。故润字，象润者离王土、出国门、渡远洋三事。古人云，三十六计走为上。今人曰，三十六行润为上。

昔有曾子三省吾身，今之润者亦日答五问。日答五问，即所谓「日五问」，亦称之为「润」。何五问者？金、木、水、火、土五行之问。具五行则润。

第一问，润之金足否？古人云，贫贱不能移。故天将降大润于是人也，必先苦其心志、劳其筋骨、饿其体肤、空乏其金，以验润者之心诚否。凡心诚者，积其金于大中华，置其房于温哥华。

第二问，润之木具否？木者乃通关之文书、载具也。然通关文牒非人人可得，故必以「自东土大唐而来，前往西天留学取经，扬我大唐之国威」为由。凡润者，无不居阿尔卑斯山之高则忧其民，处德克萨斯州之远则忧其君。是故润者必先天下之润而润，后天下之忧而忧。

第三问，润之水饮否？润学之要义，以水为大。欲润者需舌灿莲花、心如坚冰。昔汉高祖视其翁为敌翁，心若坚冰，舌灿莲花，方成汉家霸业，大丈夫应如是！水，至柔亦至坚，润虽难，润者之心日坚，必能水滴石穿，攻无不克。

第四问，润之火灭否？火乃润者之大忌。凡大火之事必有妖，大火之中介费必高。是故智者唯恐不能避之，润者反其道而行之，能者见其势而乘之。润路漫漫，谨防受骗。

第五问，润之土定否？先祖之润三，走西口、闯关东、下南洋；今吾辈之润亦三，闯东洋、渡西洋、下南洋。东洋诸国，日韩为近；然东洋虽近，不若西洋欧美之盛；南洋诸国，虽不久居，亦可小住。

噫！润者之心，日益坚固。树挪死，人挪活。先祖遇灾，其人尚能走西口、闯关东、下南洋，以求自保；西夷爱尔兰之民无以为生计，尚能远渡西洋，求生美洲。其留居故土者，死伤无数，惨绝人寰。故土难舍，其民之过乎？其君之过也！前人不睱自哀，而后人哀之；后人哀之而不鉴之，亦使后人复哀后人也！

**Comment by the-run-philosophy** [comment]
可提交pr

**Comment by EnderTheCoder** [comment]
这不放在readme很是不认可

**Comment by the-run-philosophy** [comment]
已收录
