### ISSUE TITLE
Any Wechat group? 

### ISSUE THREAD

**Issue by JixiangSoong** [The-Run-Philosophy-Organization/run#11]
Wechat groups are necessary for studying 'The-Run-Philosophy'.

**Comment by jdhao** [comment]
??

**Comment by Daniel-zb** [comment]
Using wechat to set a group is quite dangerous.

**Comment by Daniel-zb** [comment]
Using wechat to build a group is quite dangerous.

**Comment by christorange** [comment]
If u really think so, u r not suitable to run. Just forget this repo.

**Comment by ILuckyPig** [comment]
are u kidding me?!

**Comment by Himself65** [comment]
We are not planning to create an **official** WeChat group. You can do this by yourself.

Closing
