### ISSUE TITLE
《思维的误区：从“沉没成本谬误”到“损失厌恶情结”》

### ISSUE THREAD

**Issue by GentlemanXu** [The-Run-Philosophy-Organization/run#122]
沉没成本在 润 和 转专业 当中都是非常常见的一个问题，可以考虑转载编程随想的的这篇文章

[思维的误区：从“沉没成本谬误”到“损失厌恶情结”](https://program-think.blogspot.com/2014/06/sunk-cost-fallacy-and-loss-aversion.html)
文章目录
[★啥是“沉没成本”？](https://program-think.blogspot.com/2014/06/sunk-cost-fallacy-and-loss-aversion.html#head-1)
[★啥是“沉没成本谬误”？](https://program-think.blogspot.com/2014/06/sunk-cost-fallacy-and-loss-aversion.html#head-2)
[★“沉没成本谬误”举例](https://program-think.blogspot.com/2014/06/sunk-cost-fallacy-and-loss-aversion.html#head-3)
[★“沉没成本谬误”的心理成因](https://program-think.blogspot.com/2014/06/sunk-cost-fallacy-and-loss-aversion.html#head-4)
[★先看几个小测试](https://program-think.blogspot.com/2014/06/sunk-cost-fallacy-and-loss-aversion.html#head-5)
[★什么是“损失憎恶/损失规避”情结？](https://program-think.blogspot.com/2014/06/sunk-cost-fallacy-and-loss-aversion.html#head-6)
[★你知道“对损失的厌恶”有多强烈吗？](https://program-think.blogspot.com/2014/06/sunk-cost-fallacy-and-loss-aversion.html#head-7)
[★如何用“损失憎恶情结”进行误导、忽悠和洗脑？](https://program-think.blogspot.com/2014/06/sunk-cost-fallacy-and-loss-aversion.html#head-8)
[★结尾](https://program-think.blogspot.com/2014/06/sunk-cost-fallacy-and-loss-aversion.html#head-9)

**Comment by the-run-philosophy** [comment]
请转换为PR提交，
