### ISSUE TITLE
歡迎申請美國國家民主基金會獎學金

### ISSUE THREAD

**Issue by muxivcom** [The-Run-Philosophy-Organization/run#124]
金
計劃
Reagan-Fascell (裡根-法塞爾)民主研究員計劃是國際性學術交流計劃，為來自全世界的從業者、學者以及記者提供為期五個月獨立研究世界各地的民主挑戰的機會，主辦方為位於華盛頓特區的美 國國家民主基金會 (NED)。駐在期間，研究員們反思各自的經驗；與同事並肩工作；進行研究及編撰工作；思考最佳實踐和經驗教訓；在全球民主支持者網絡內發展專業聯繫.

支持
本計劃專屬於NED 的民主研究國際論壇，提供豐富的鑽研支持以達到教育交流及專業培養的目的。該論壇還出版期刊 Journal of Democracy（《民主雜誌》），召開會議，並提供訪問 NED 圖書館的權限。計劃提供由助理研究員負責的支持，並協助研究員與華盛頓的倡導團體、媒體、學院及政治社團發展聯繫。所有獎學金均包括每月生活津貼、健康保險以及往返旅行補貼。計劃不包括其隨行家屬或其他親屬的財務補貼.

參與
該計劃每年舉行兩次為期五個月的學人研究進程，在此期間研究員需將全部時間用於他們的研究項目。從業者主要集中研究在其感興趣的國家發展民主政治的策略 及最佳實踐，而學者則進行原創研究並將其成果發表。項目可從經濟、政治、社會、法律和文化等各方面探討民主政治的發展，並包括一些相關的方法論。本計劃為協助研究員，也將籌劃部分行程，比如 NED 介紹及其合作機構。研究員在駐期間需展示其工作成果並撰寫相關研究文章 .

資格
獎學金主要目標人群為來自發展中民主國家或致力於發展民主的國家的人士。來自美國等成熟民主國家的知名學者亦可以申請。意欲申請的從業者和記者需在 各自領域擁有相當的工作經驗，學者則在申請時需擁有博士學位或同等學術水平。該計劃不支持專業培訓、田野工作、學生求學學費、或實際項目實施。必須能夠理解和運用英語.

日期
秋季研討會： 10 月至年 2 月。春季研討會: 3 月至 7 月.
詳情請訪問 www.ned.org 或發送電子郵件至 fellowships@ned.org.

**Comment by the-run-philosophy** [comment]
和本github无关
