### ISSUE TITLE
润学：Runnology

### ISSUE THREAD

**Issue by QMHTMY** [The-Run-Philosophy-Organization/run#127]
Run、Ran、Runnable、Runnology。润学对应词汇，建议扩充英文对应单词的词义，加入润这个意思。

**Comment by the-run-philosophy** [comment]
可以去urbandictionary贡献

**Comment by QMHTMY** [comment]
我的意思是本 repo 可以为这些单词启用这些意思，便于交流，只是建议，哈哈！
