### ISSUE TITLE
扛着红旗卖国也好意思"润"？我看是run，跑吧？

### ISSUE THREAD

**Issue by CrazyPandas** [The-Run-Philosophy-Organization/run#128]
@[lengfengwujing](https://github.com/lengfengwujing) The traitor

**Comment by jiayouba233** [comment]
> @[lengfengwujing](https://github.com/lengfengwujing) The traitor

润不等于跑路？

https://www.twitter.com/xmt20065/status/1489632783647469569

**Comment by the-run-philosophy** [comment]
我会在今天写一个“为什么要润，而不是留下”的文章专门回答你这个问题。尽情期待

**Comment by CrazyPandas** [comment]
> > @[lengfengwujing](https://github.com/lengfengwujing) The traitor
> 
> 润不等于跑路？
> 
> https://www.twitter.com/xmt20065/status/1489632783647469569

是跑路的话我就可以理解了，甚至希望你们快点跑。只是这个人的名字和头像用在这个项目上让我觉得讽刺，像个小丑 @[lengfengwujing](https://github.com/lengfengwujing)

**Comment by AxelTchaikovsky** [comment]
> > > @[lengfengwujing](https://github.com/lengfengwujing) The traitor
> > 
> > 
> > 润不等于跑路？
> > https://www.twitter.com/xmt20065/status/1489632783647469569
> 
> 是跑路的话我就可以理解了，甚至希望你们快点跑。只是这个人的名字和头像用在这个项目上让我觉得讽刺，像个小丑 @[lengfengwujing](https://github.com/lengfengwujing)

It's sarcasm man
