### ISSUE TITLE
2021南京工业大学飞跃手册

### ISSUE THREAD

**Issue by cafferychen777** [The-Run-Philosophy-Organization/run#129]
https://github.com/yaoshun123/FLY_NJTech/raw/main/2021-%E5%8D%97%E4%BA%AC%E5%B7%A5%E4%B8%9A%E5%A4%A7%E5%AD%A6%E6%9C%AC%E7%A7%91%E7%94%9F%E9%A3%9E%E8%B7%83%E6%89%8B%E5%86%8C%EF%BC%88%E7%AC%AC%E4%B8%80%E7%89%88%EF%BC%89.pdf

**Comment by httpsColon** [comment]
祖国配不上你们是吧，滚😠回来死个妈

**Comment by jiayouba233** [comment]
> 祖国配不上你们是吧，滚😠回来死个妈

”当先锋队内部混入了资产阶级和一大堆不信马列的人的时候，当人大政协里头工农代表不足三分之一以致无产阶级专政名存实亡的时候，当农民工讨薪非法而劳动法变成一纸空文的时候，我们都知道我们遭受了最为可耻的背叛。“ https://twitter.com/xmt20065/status/1489632783647469569

**Comment by the-run-philosophy** [comment]
谢谢补充。下次可以直接提交pr
