### ISSUE TITLE
学英语的文件夹在哪里？

### ISSUE THREAD

**Issue by stackunderflow111** [The-Run-Philosophy-Organization/run#136]
似乎没有？学英语还是很重要的吧

**Comment by the-run-philosophy** [comment]
首页更新了 [学好英文的十个步骤](https://github.com/The-Run-Philosophy-Organization/run/blob/main/%E6%B6%A6%E5%AD%A6%E6%96%B9%E6%B3%95%E8%AE%BA/%E5%89%8D%E6%9C%9F%E5%87%86%E5%A4%87/%E8%8B%B1%E8%AF%AD%E5%AD%A6%E4%B9%A0/%E5%AD%A6%E5%A5%BD%E8%8B%B1%E6%96%87%E7%9A%84%E5%8D%81%E4%B8%AA%E6%AD%A5%E9%AA%A4.md)

**Comment by the-run-philosophy** [comment]
欢迎补充
