### ISSUE TITLE
请将仓库转移至私有仓库. Github 不是一个政治平台

### ISSUE THREAD

**Issue by G11Max** [The-Run-Philosophy-Organization/run#151]
请不要利用公共平台阐述自己的政治观点。

Github 本身是无辜的 求求你 放过她吧， 自己搭一个私有仓库花不了几个钱儿， 如果因此被屏蔽将是技术人的灾难.

**Comment by the-run-philosophy** [comment]
如果技术连你的思想都无法解放，那你这技术也是白搭。
我赞同全世界向法西斯技术禁运。如你承认你是法西斯的话

**Comment by the-run-philosophy** [comment]
希望你自己好好反省自己匍匐苟且的习惯。
