### ISSUE TITLE
真他妈的晦气

### ISSUE THREAD

**Issue by ggymm** [The-Run-Philosophy-Organization/run#156]
在trending看见这个，真他妈的丢人，晦气，呸

**Comment by jiayouba233** [comment]
您要是不认同此项目可以关掉不看，而不是来发垃圾Issues

**Comment by ggymm** [comment]
> 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues

你可以发表为什么我不可以评论，再说这又不是技术仓库，issue不就是评论自己想法的？

**Comment by jiayouba233** [comment]
> > 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues
> 
> 你可以发表为什么我不可以评论，再说这又不是技术仓库，issue不就是评论自己想法的？

issue是用来提问的，想法请转Discussion

**Comment by ggymm** [comment]
> > > 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues
> > 
> > 
> > 你可以发表为什么我不可以评论，再说这又不是技术仓库，issue不就是评论自己想法的？
> 
> issue是用来提问的，想法请转Discussion

issue的作用哪里定义的，麻烦指路？是那条规定说不能评论自己对存储库看法的？

**Comment by upojzsb** [comment]
> > > > 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues
> > > 
> > > 
> > > 你可以发表为什么我不可以评论，再说这又不是技术仓库，issue不就是评论自己想法的？
> > 
> > 
> > issue是用来提问的，想法请转Discussion
> 
> issue的作用哪里定义的，麻烦指路？是那条规定说不能评论自己对存储库看法的？

您如果有兴趣可以研究一下 GitHub 关于 issue 作用的介绍。
https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues

您如果没有兴趣自行研究，我在摘抄上述文档中的一段：
> Use GitHub Issues to track ideas, feedback, tasks, or bugs for work on GitHub.

**Comment by raceychan** [comment]
> > 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues
> 
> 
> 
> 你可以发表为什么我不可以评论，再说这又不是技术仓库，issue不就是评论自己想法的？

支猪连issue都干啥用的搞不清楚， github还是别玩了，建议去百度贴吧

**Comment by ggymm** [comment]
> Use GitHub Issues to track ideas, feedback, tasks, or bugs for work on GitHub.

所以，我发表我的idea和feedback，又有什么问题？

**Comment by ggymm** [comment]
> > > 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues
> > 
> > 
> > 你可以发表为什么我不可以评论，再说这又不是技术仓库，issue不就是评论自己想法的？
> 
> 支猪连issue都干啥用的搞不清楚， github还是别玩了，建议去百度贴吧

狗汉奸，滚，he，tui

**Comment by ggymm** [comment]
> > > 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues
> > 
> > 
> > 你可以发表为什么我不可以评论，再说这又不是技术仓库，issue不就是评论自己想法的？
> 
> 支猪连issue都干啥用的搞不清楚， github还是别玩了，建议去百度贴吧

另外该滚的是你们，谁家狗管不好，把Github当成什么了，到处乱拉乱尿

**Comment by jiayouba233** [comment]
> > > > 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues
> > > 
> > > 
> > > 你可以发表为什么我不可以评论，再说这又不是技术仓库，issue不就是评论自己想法的？
> > 
> > 
> > 支猪连issue都干啥用的搞不清楚， github还是别玩了，建议去百度贴吧
> 
> 另外该滚的是你们，谁家狗管不好，把Github当成什么了，到处乱拉乱尿

您发这个Issue的性质与之前React项目因为支持乌克兰被国人开Issue骂开发者没什么区别......

**Comment by bulai0408** [comment]
看起来你的出发点是在trending里面看到了然后觉得家丑不可外扬？“另外把github当成什么了”建议你去女装github同性github等等全部评价一遍，github是很高贵人上人才能用吗？

**Comment by ggymm** [comment]
> 看起来你的出发点是在trending里面看到了然后觉得家丑不可外扬？“另外把github当成什么了”建议你去女装github同性github等等全部评价一遍，github是很高贵人上人才能用吗？

这算什么家丑？可不算一家人，可不熟，可别乱攀关系。
另外女装同性算是小圈子自娱自乐，起码不恶心我。至于这玩意的Readme，什么核心宗教，垃圾玩意

**Comment by bulai0408** [comment]
> > 看起来你的出发点是在trending里面看到了然后觉得家丑不可外扬？“另外把github当成什么了”建议你去女装github同性github等等全部评价一遍，github是很高贵人上人才能用吗？
> 
> 这算什么家丑？可不算一家人，可不熟，可别乱攀关系。 另外女装同性算是小圈子自娱自乐，起码不恶心我。至于这玩意的Readme，什么核心宗教，垃圾玩意

你的头像恶心我了，这可怎么办呢

**Comment by ggymm** [comment]
> > > 看起来你的出发点是在trending里面看到了然后觉得家丑不可外扬？“另外把github当成什么了”建议你去女装github同性github等等全部评价一遍，github是很高贵人上人才能用吗？
> > 
> > 
> > 这算什么家丑？可不算一家人，可不熟，可别乱攀关系。 另外女装同性算是小圈子自娱自乐，起码不恶心我。至于这玩意的Readme，什么核心宗教，垃圾玩意
> 
> 你的头像恶心我了，这可怎么办呢

你就会说这个了？我还以为能憋出什么屁呢

**Comment by raceychan** [comment]
> > > > 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues
> > > 
> > > 
> > > 你可以发表为什么我不可以评论，再说这又不是技术仓库，issue不就是评论自己想法的？
> > 
> > 
> > 支猪连issue都干啥用的搞不清楚， github还是别玩了，建议去百度贴吧
> 
> 另外该滚的是你们，谁家狗管不好，把Github当成什么了，到处乱拉乱尿

你不仅自己愿意一辈子当蜘蛛，别人润你还要骂， 那么请解释一下你为什么要在美国人开的美国公司收购的美国网站上用英文写美国人发明的编程语言呀，蜘蛛？不是你美国爹，说不定你现在还在树上摘香蕉呢。

**Comment by ggymm** [comment]
> > > > > 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues
> > > > 
> > > > 
> > > > 你可以发表为什么我不可以评论，再说这又不是技术仓库，issue不就是评论自己想法的？
> > > 
> > > 
> > > 支猪连issue都干啥用的搞不清楚， github还是别玩了，建议去百度贴吧
> > 
> > 
> > 另外该滚的是你们，谁家狗管不好，把Github当成什么了，到处乱拉乱尿
> 
> 你不仅自己愿意一辈子当蜘蛛，别人润你还要骂， 那么请解释一下你为什么要在美国人开的美国公司收购的美国网站上用英文写美国人发明的编程语言呀，蜘蛛？不是你美国爹，说不定你现在还在树上摘香蕉呢。

弱智言论，狗汉奸，多回你一句都多余，有多远滚多远，he，tui

**Comment by suixinyuan99** [comment]
> > > > 看起来你的出发点是在trending里面看到了然后觉得家丑不可外扬？“另外把github当成什么了”建议你去女装github同性github等等全部评价一遍，github是很高贵人上人才能用吗？
> > > 
> > > 
> > > 这算什么家丑？可不算一家人，可不熟，可别乱攀关系。 另外女装同性算是小圈子自娱自乐，起码不恶心我。至于这玩意的Readme，什么核心宗教，垃圾玩意
> > 
> > 
> > 你的头像恶心我了，这可怎么办呢
> 
> 你就会说这个了？我还以为能憋出什么屁呢

实际上他的回复都是在针对你的核心论点进行攻击，很遗憾你没有反击或者针对性回复。

当你说“把Github当成什么了”，他针对这点给出了疑问“女装/同性GitHub你为什么不批判”——意指你并不是真的因为“GitHub机制被滥用”而愤怒。（当然我们都知道你确实不是）
当你给出了第二个理由“起码不恶心我”的时候（相信这确实是你的真实理由），他回复的是“你也恶心到我了，这可怎么办啊”——意指如果“单方面对某事/某物感到恶心就有正当理由提issue开骂”的话，那我们是不是也该说你晦气，也可以骂你？（实际上大家似乎也真的开骂了，这很逻辑自洽）

其实他的攻击点很明确，并非你所说的“憋不出什么屁”，可能没有理解的是你。

其实我更不理解的是，“劝人润”并不是什么“反动标语”：因为“你觉得不好你可以滚”一直是常用话术，为什么大家真的滚了，你要着急呢？
我觉得自信是一个很优秀的品质，相信自己的国家本身是一种很伟大的自信。如果你坚信自己的国家正在、或即将伟大或走在伟大的道路上，你要有自信耻笑那些偏离了正确道路的人，你要有自信去耻笑那些有好地方不呆去水深火热的地狱的蠢猪，为什么要觉得他们晦气呢？
你要相信真理是不言自明的，是终将清晰的，做出了错误决定的人将会在尘埃落定后受到历史的惩罚，在浅色的床单上痛哭流涕。

如果你相信这里更好，要有自信。如果你相信别处更好，出于善意没必要对奔向更好生活的人妄加指责。
如果你被植入了“这里更好，你要爱这里”的想法，但现实与理智却在潜意识里告知了你相反的逻辑，并且每每尝试思考或者看其他人思考的产物后，都会因为这种不自洽带来的分裂的痛苦的话，请不要将这种分裂的痛苦简单的归咎给让你思考的人，而是要么抛弃大脑尝试彻底的放弃思考，或者认真的用大脑把这件事一次性想明白。

而且我说实话，历史是真的有可能证明，润出去的人未必比呆在这里更好的。
我认识的很多人都觉得比特币是个谎言，是个击鼓传花的游戏（实际上我现在也坚信）。然而事实就是，被庞氏骗局骗来的，最坚定的韭菜反而发了家。
所以没人知道，坚信“这里更好，我要爱这里”的人是不是也会受到幸运的青睐，而轮到费尽心思润出去的倒霉蛋在浅色床单上痛哭，你要有自信。

**Comment by ggymm** [comment]
可笑至极，我只是骂了一句，你帮我想了这么多，真是辛苦你了呢，呵呵

**Comment by jiayouba233** [comment]
> 可笑至极，我只是骂了一句，你帮我想了这么多，真是辛苦你了呢，呵呵

[当先锋队内部混入了资产阶级和一大堆不信马列的人的时候，当人大政协里头工农代表不足三分之一以致无产阶级专政名存实亡的时候，当农民工讨薪非法而劳动法变成一纸空文的时候，我们都知道我们遭受了最为可耻的背叛。](https://mobile.twitter.com/xmt20065/status/1489632783647469569)

**Comment by jiayouba233** [comment]
这算涉及政治的回复（

**Comment by suixinyuan99** [comment]
> 可笑至极，我只是骂了一句，你帮我想了这么多，真是辛苦你了呢，呵呵

说实话我挺期待你的回复的，但很遗憾“这么多”的字也没有促进你的进一步思考，而是仍然留下了一个经典的meme
“你发了这么多，你好认真啊，你急了”
我其实能猜到，但还是挺失望的，就这样吧，我也不期待你进一步说什么了。

其实我并没有“帮你想这么多”，**我只是思考了一下，然后把我思考的内容如实的告诉了你而已**。
看起来多，只是因为我思考的内容本身就是这么多。
而且如果你真的思考过的话，你会意识到**这些内容并不多**，思考这些不会占用你一分钟以上的时间，反而是把这些字敲出来的时间更多。（就跟写代码一样，有些内容瞬间想到但要机械工作许久，有些内容要想半天写起来却很快，这个就是前者）
实际上我看到的很多短回复反而不可理喻——我会想_“这就是你全部想说的吗？你看完这么多文字大脑中真的只能想到‘晦气、tui’吗？那你的大脑平常都在空转吗？你到底在思考什么？”_

而且说句实话，这种回复本身没有任何意义，隔着屏幕跟你对话我甚至都没法给你通过图灵测试。
“汉奸”“晦气”，这些都是别人的思想，甚至连“你回复这么多你急了”这个逻辑都是司空见惯的东西，这是你自己思考的产物吗——“打了这么多字，你急了！”，你能想到的就这个？你对内容真的没什么想说的吗？
而且不出意外，你根本不会读这么大段的文字，如果读完并且理解了我在说什么，恐怕下一句也是“你这种人不值得我回复/你这种人不值得我思考”罢，有时候我怀疑是不是网络背后都是谷歌搞的机器人。

**Comment by bulai0408** [comment]
> > 可笑至极，我只是骂了一句，你帮我想了这么多，真是辛苦你了呢，呵呵
> 
> 说实话我挺期待你的回复的，但很遗憾“这么多”的字也没有促进你的进一步思考，而是仍然留下了一个经典的meme “你发了这么多，你好认真啊，你急了” 我其实能猜到，但还是挺失望的，就这样吧，我也不期待你进一步说什么了。
> 
> 其实我并没有“帮你想这么多”，**我只是思考了一下，然后把我思考的内容如实的告诉了你而已**。 看起来多，只是因为我思考的内容本身就是这么多。 而且如果你真的思考过的话，你会意识到**这些内容并不多**，思考这些不会占用你一分钟以上的时间，反而是把这些字敲出来的时间更多。（就跟写代码一样，有些内容瞬间想到但要机械工作许久，有些内容要想半天写起来却很快，这个就是前者） 实际上我看到的很多短回复反而不可理喻——我会想_“这就是你全部想说的吗？你看完这么多文字大脑中真的只能想到‘晦气、tui’吗？那你的大脑平常都在空转吗？你到底在思考什么？”_
> 
> 而且说句实话，这种回复本身没有任何意义，隔着屏幕跟你对话我甚至都没法给你通过图灵测试。 “汉奸”“晦气”，这些都是别人的思想，甚至连“你回复这么多你急了”这个逻辑都是司空见惯的东西，这是你自己思考的产物吗——“打了这么多字，你急了！”，你能想到的就这个？你对内容真的没什么想说的吗？ 而且不出意外，你根本不会读这么大段的文字，如果读完并且理解了我在说什么，恐怕下一句也是“你这种人不值得我回复/你这种人不值得我思考”罢，有时候我怀疑是不是网络背后都是谷歌搞的机器人。

其实吧，如果算他是程序员的话，他的回复让人觉得很无助，就好像需要救助一样，他甚至没有经过思考，他甚至只是想骂人，懒得思考。世界上值得他骂的那么多，被他看不惯的那么多，而他迅速听到了这个repo，迅速过来在多个issue下面骂，周日竟然还在工作，做的还很凌厉，至少这个方面让人肃然起敬。

**Comment by ggymm** [comment]
> > 可笑至极，我只是骂了一句，你帮我想了这么多，真是辛苦你了呢，呵呵
> 
> 说实话我挺期待你的回复的，但很遗憾“这么多”的字也没有促进你的进一步思考，而是仍然留下了一个经典的meme “你发了这么多，你好认真啊，你急了” 我其实能猜到，但还是挺失望的，就这样吧，我也不期待你进一步说什么了。
> 
> 其实我并没有“帮你想这么多”，**我只是思考了一下，然后把我思考的内容如实的告诉了你而已**。 看起来多，只是因为我思考的内容本身就是这么多。 而且如果你真的思考过的话，你会意识到**这些内容并不多**，思考这些不会占用你一分钟以上的时间，反而是把这些字敲出来的时间更多。（就跟写代码一样，有些内容瞬间想到但要机械工作许久，有些内容要想半天写起来却很快，这个就是前者） 实际上我看到的很多短回复反而不可理喻——我会想_“这就是你全部想说的吗？你看完这么多文字大脑中真的只能想到‘晦气、tui’吗？那你的大脑平常都在空转吗？你到底在思考什么？”_
> 
> 而且说句实话，这种回复本身没有任何意义，隔着屏幕跟你对话我甚至都没法给你通过图灵测试。 “汉奸”“晦气”，这些都是别人的思想，甚至连“你回复这么多你急了”这个逻辑都是司空见惯的东西，这是你自己思考的产物吗——“打了这么多字，你急了！”，你能想到的就这个？你对内容真的没什么想说的吗？ 而且不出意外，你根本不会读这么大段的文字，如果读完并且理解了我在说什么，恐怕下一句也是“你这种人不值得我回复/你这种人不值得我思考”罢，有时候我怀疑是不是网络背后都是谷歌搞的机器人。

因为一文不值，一点意义都没有，我读什么，全篇都是你在那臆想，你以为我怎样怎样，然后自己自言自语，我回什么？有什么可回的？

**Comment by bulai0408** [comment]
> > > 可笑至极，我只是骂了一句，你帮我想了这么多，真是辛苦你了呢，呵呵
> > 
> > 
> > 说实话我挺期待你的回复的，但很遗憾“这么多”的字也没有促进你的进一步思考，而是仍然留下了一个经典的meme “你发了这么多，你好认真啊，你急了” 我其实能猜到，但还是挺失望的，就这样吧，我也不期待你进一步说什么了。
> > 其实我并没有“帮你想这么多”，**我只是思考了一下，然后把我思考的内容如实的告诉了你而已**。 看起来多，只是因为我思考的内容本身就是这么多。 而且如果你真的思考过的话，你会意识到**这些内容并不多**，思考这些不会占用你一分钟以上的时间，反而是把这些字敲出来的时间更多。（就跟写代码一样，有些内容瞬间想到但要机械工作许久，有些内容要想半天写起来却很快，这个就是前者） 实际上我看到的很多短回复反而不可理喻——我会想_“这就是你全部想说的吗？你看完这么多文字大脑中真的只能想到‘晦气、tui’吗？那你的大脑平常都在空转吗？你到底在思考什么？”_
> > 而且说句实话，这种回复本身没有任何意义，隔着屏幕跟你对话我甚至都没法给你通过图灵测试。 “汉奸”“晦气”，这些都是别人的思想，甚至连“你回复这么多你急了”这个逻辑都是司空见惯的东西，这是你自己思考的产物吗——“打了这么多字，你急了！”，你能想到的就这个？你对内容真的没什么想说的吗？ 而且不出意外，你根本不会读这么大段的文字，如果读完并且理解了我在说什么，恐怕下一句也是“你这种人不值得我回复/你这种人不值得我思考”罢，有时候我怀疑是不是网络背后都是谷歌搞的机器人。
> 
> 因为一文不值，一点意义都没有，我读什么，全篇都是你在那臆想，你以为我怎样怎样，然后自己自言自语，我回什么？有什么可回的？
People from all over the world, this turned out to be a member of China, this turned out to be a programmer in China, I suggest you open the translation to see the quality of our people.

**Comment by ggymm** [comment]
太经典了，经典扣帽子，经典假设立场，经典假设情境，你们还有点啥别的说的不？

**Comment by Bian-Sh** [comment]
> 太经典了，经典扣帽子，经典假设立场，经典假设情境，你们还有点啥别的说的不？

如果这群人不把 不尔什维克 拿来说事，就算图文批判社会乱象，也不至于上升到政治层面。
你要润，你心照不宣的润就得了，没人拦得了

**Comment by lwd-temp** [comment]
讨论 #153 也谈论了这个问题，这里已经出现人身攻击了，请注意GitHub社区守则

**Comment by ggymm** [comment]
> > 太经典了，经典扣帽子，经典假设立场，经典假设情境，你们还有点啥别的说的不？
> 
> 如果这群人不把 不尔什维克 拿来说事，就算图文批判社会乱象，也不至于上升到政治层面。 你要润，你心照不宣的润就得了，没人拦得了

我还反感readme里面这段
>并成为新中国人的核心宗教，核心信念。 中国人的润将会持续至少100年，直到2122年为止。而本目录，也将会持续100年，直到山无棱、天地合，才敢与润绝。

这算个什么玩意

**Comment by bulai0408** [comment]
《他甚至不反感新闻联播作假和某人视察上海天台拍新闻联播素材》

**Comment by czy-moyu** [comment]
上面这小丑如果不是既得利益者那就是真的蠢。

**Comment by the-run-philosophy** [comment]
开conversation讨论

**Comment by ggymm** [comment]
> 上面这小丑如果不是既得利益者那就是真的蠢。

确实，小丑这个评价确实合适

**Comment by Bian-Sh** [comment]
> > 上面这小丑如果不是既得利益者那就是真的蠢。
> 
> 确实，小丑这个评价确实合适

你大概分不清敌友了，这个人在说咱们是小丑呢

既得利益者是 润 中的批判对象，或者说是他们声称的[润]所 不适用 对象
我觉得求同存异，有想法就去试试，哪儿都有负面东西，自己去体验。
当然，不支持单方面的黑，自己黑自己国人更让人难受，如果你傲娇那你亦可以想着改善他。

**Comment by InuYasha000** [comment]
> 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues

哪里都看得到你，香蕉人？

**Comment by InuYasha000** [comment]
> > > 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues
> > 
> > 
> > 你可以发表为什么我不可以评论，再说这又不是技术仓库，issue不就是评论自己想法的？
> 
> 支猪连issue都干啥用的搞不清楚， github还是别玩了，建议去百度贴吧

香蕉人还高傲哦，支猪都来了，你爸爸妈妈都run完了吗？你这么骂你祖先可不好哦

**Comment by jiayouba233** [comment]
> > 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues
> 
> 哪里都看得到你，香蕉人？

直接上来人身攻击可还行（
我怎么就不能发表自己的建议了？我并没有攻击/辱骂 他人吧

**Comment by codesniper47** [comment]
> > > 您要是不认同此项目可以关掉不看，而不是来发垃圾Issues
> > 
> > 
> > 你可以发表为什么我不可以评论，再说这又不是技术仓库，issue不就是评论自己想法的？
> 
> 支猪连issue都干啥用的搞不清楚， github还是别玩了，建议去百度贴吧

哦，那你的认知中你是啥？
渴望有个人样的蠢猪？
还是人猪杂交的杂种，然后你的野爹不认你？
