### ISSUE TITLE
README 中一条链接失效

### ISSUE THREAD

**Issue by AxelTchaikovsky** [The-Run-Philosophy-Organization/run#167]
主readme中这条链接打开repo已经不在了
[海专精算比我懂更比你懂](https://github.com/The-Run-Philosophy-Organization/run/blob/main/%E5%BC%A0%E7%BB%B4%E4%B8%BA%E9%99%88%E5%B9%B3%E6%9B%B9%E4%B8%B0%E6%B3%BD%E7%AD%89%E7%9F%A5%E5%90%8D%E8%A8%80%E8%AE%BA%E6%94%B6%E9%9B%86/%E6%B5%B7%E4%B8%93%E7%B2%BE%E7%AE%97%E6%AF%94%E6%88%91%E6%87%82%E6%9B%B4%E6%AF%94%E4%BD%A0%E6%87%82.jpg)

**Comment by the-run-philosophy** [comment]
fixed
