### ISSUE TITLE
词语勘误

### ISSUE THREAD

**Issue by xiaofuyesnew** [The-Run-Philosophy-Organization/run#172]
[文本地址](https://github.com/The-Run-Philosophy-Organization/run/blob/main/%E5%93%B2%E5%AD%A6%E6%A6%82%E5%BF%B5/%E4%B8%BA%E4%BD%95%E8%80%8C%E6%B6%A6.md)

> ## 布尔什维克（自上而下） vs 自下而上
> ...
> - 引进mrna疫苗与否

其中 `mrna` 应为 `mRNA`.

声明：勘误仅出于专业表述的角度，并不代表本人认同本仓库的概念和逻辑。

**Comment by the-run-philosophy** [comment]
请提交PR

**Comment by jiayouba233** [comment]
> [文本地址](https://github.com/The-Run-Philosophy-Organization/run/blob/main/%E5%93%B2%E5%AD%A6%E6%A6%82%E5%BF%B5/%E4%B8%BA%E4%BD%95%E8%80%8C%E6%B6%A6.md)
> 
> > ## 布尔什维克（自上而下） vs 自下而上
> > ...
> > 
> > * 引进mrna疫苗与否
> 
> 其中 `mrna` 应为 `mRNA`.
> 
> 声明：勘误仅出于专业表述的角度，并不代表本人认同本仓库的概念和逻辑。

已经进行修正
