### ISSUE TITLE
别的不说，请问那些飞跃手册征求过所有当事人的同意么？

### ISSUE THREAD

**Issue by zyubupt** [The-Run-Philosophy-Organization/run#176]
据我所知，飞跃手册一般是发在学校内部论坛，供本校后来者参考的资料。你一个创建者，包括那些提供飞跃手册的contributor征求过写飞跃手册中的作者们的意愿了么，特别是把飞跃手册用在如此政治的repo中？

**Comment by zyubupt** [comment]
特别是里面还有各种学生的真实姓名和联系方式

**Comment by the-run-philosophy** [comment]
`飞跃手册一般是发在学校内部论坛，供本校后来者参考的资料` 显然不是，这些文件都是公开ACCESS的PDF

**Comment by zyubupt** [comment]
我是在问你取得了当事人的同意么？
和这些是不是公开的有关系？

**Comment by zyubupt** [comment]
问题是征求过当事人的同意没有？和这些文件是不是公开的没关系。
算了，我也是真够无聊的，还来填个issue，当事人看到了自己处理吧

**Comment by Trliu18** [comment]
如图，上面明确写了仅限校内传阅，切勿公开发布，里面封页也写得有，只是因为没有放在内网所以可以直接access到。这里面涉及到了同学的真实姓名和联系方式及个人隐私，希望能够撤掉，或者至少应该经过负责人的同意。
<img width="628" alt="飞跃手册" src="https://user-images.githubusercontent.com/87387649/173253249-fa1b422d-3ee6-43ef-8d9e-33272138de94.png">
