### ISSUE TITLE
不建议加那么多攻略性板块

### ISSUE THREAD

**Issue by BridgeQZH** [The-Run-Philosophy-Organization/run#192]
搞到最后成了一亩三分地的各种经验大汇总了，失去了本repo的特殊性。
另外好多文件夹里面的内容，确定不是各路翻车新闻大汇总？
勿忘初心，别到最后做成了一个四不像了。

**Comment by mczhuge** [comment]
当看到 “并成为新中国人的核心宗教，核心信念。 中国人的润将会持续至少100年，直到2122年为止。” 后，你确定它还有初心吗。直接把攻略/建议变成了精心策划的政治repo了。

**Comment by jiayouba233** [comment]
这部分文件夹是我写的，我的想法是：展示国内媒体的翻车以及全过程民主，算是劝人们润？
在2020年，中国真能算世界上最好的国家了（对疫情的防控等等）
但在过去的2年间，我见识到了[彭帅](https://zh.wikipedia.org/zh-cn/%E5%BD%AD%E5%B8%A5%E6%8C%87%E6%8E%A7%E5%BC%B5%E9%AB%98%E9%BA%97%E6%80%A7%E9%86%9C%E8%81%9E%E4%BA%8B%E4%BB%B6),[铁链女](https://zh.wikipedia.org/zh-cn/%E5%BE%90%E5%B7%9E%E5%85%AB%E5%AD%A9%E6%AF%8D%E8%A6%AA%E4%BA%8B%E4%BB%B6)官方前前后后发了5次通报，[Luogu把共产主义等内容列为敏感内容](https://luogulo.gq/show.php?url=https://www.luogu.com.cn/discuss/388043)

**Comment by the-run-philosophy** [comment]
未来会有一次目录组织结构的大改。希望你提建议？

**Comment by EzioKissshot** [comment]
没有攻略，怎么帮助想润的人执行？希望建议能更有建设性

一亩三分地看贴还要积分，本来就不是所有人都可以获取到的信息

**Comment by BridgeQZH** [comment]
> 

你说的对，我的想法也变了很多次，现在想来还是你说的比较有道理。

**Comment by BridgeQZH** [comment]
> 没有攻略，怎么帮助想润的人执行？希望建议能更有建设性
> 
> 一亩三分地看贴还要积分，本来就不是所有人都可以获取到的信息


你说的对，我的想法也变了很多次，现在想来还是你说的比较有道理。
