### ISSUE TITLE
作者身在美国，有没有一种可能：他是被胁迫的，如果不反动就遣回？

### ISSUE THREAD

**Issue by Bian-Sh** [The-Run-Philosophy-Organization/run#197]
因为这个仓库已经涉政了：布尔什维克 是列宁领导的党派，在本仓库中指代 共产党，请各位留意这个仓库的涉政本质
任何事情都是双刃剑，网络是有记忆的, 大家还是谨慎发言

能 Run 出去还好，想 Run 人家不收，舔着脸留在国内那就尴尬了
毕竟中国人最恨的是数典忘祖，汉奸叛徒和走狗

另外，也有人说到了不要拉学生进入这种漩涡中，毕竟一旦把留学与本仓库带有政治色彩的“润”发生关联，学生踊跃申请留学可能都被视为 Run ，这个仓库影响越大，效果越显著，不可谓不是害了学生团体。

再者，仓库维护者也说了，国外，也有针对国人的不友善措施，比如怀孕必须送回国啥的，所以也不必无脑黑，把这些避坑策略也补上，才是大善（前提不涉政）。

讲真，这个作者影响力还是很大，一直在关注，一周内 star  从 1K 飙升至 8K.

最后，这个作者会不会成为下一个 李洪志 呢？

PS：附上这个仓库的 Star 趋势
[![Stargazers over time](https://starchart.cc/The-Run-Philosophy-Organization/run.svg)](https://starchart.cc/The-Run-Philosophy-Organization/run)

**Comment by sakurashino** [comment]
可以请您解释一下反动是什么意思吗？

**Comment by stackunderflow111** [comment]
对，我亲眼看到CIA的人用枪顶着勃勃的脑袋

**Comment by the-run-philosophy** [comment]
你说的可太对了，全世界海外华人都是被胁迫才出国的；
而且恰恰相反，国内的人没有任何胁迫，都是衷心的，真心的，好无二心毫无保留的支持布尔什维克的至上而下的统治，并且愿意为他产生的一切铁拳、幸福和经济后果付出代价～

**Comment by Bian-Sh** [comment]
> 你说的可太对了，全世界海外华人都是被胁迫才出国的； 而且恰恰相反，国内的人没有任何胁迫，都是衷心的，真心的，好无二心毫无保留的支持布尔什维克的至上而下的统治，并且愿意为他产生的一切铁拳、幸福和经济后果付出代价～

你这样发言，会害了这个仓库的点赞群体，国外不也是有自己的政治体系的嘛，美国还美元霸权收割全世界呀。

**Comment by CrazyPandas** [comment]
天要下雨，娘要嫁人。不爱国的想跑的就让他们跑呗，咱也不稀罕。

中国特色社会主义是改革开放以来中国共产党的全部理论和实践的主题，是党和人民历尽千辛万苦、付出巨大代价取得的根本成就。中国特色社会主义最本质的特征就是中国共产党的领导，中国共产党始终代表中国最广泛人民群众的利益。

**Comment by jiayouba233** [comment]
> 天要下雨，娘要嫁人。不爱国的想跑的就让他们跑呗，咱也不稀罕。
> 
> 中国特色社会主义是改革开放以来中国共产党的全部理论和实践的主题，是党和人民历尽千辛万苦、付出巨大代价取得的根本成就。中国特色社会主义最本质的特征就是中国共产党的领导，中国共产党始终代表中国最广泛人民群众的利益。

爱中华民族 ≠ 爱国 ≠ 爱中国共产党，请分清楚这一概念

https://twitter.com/Hana_INFP/status/1516617636351594499
https://twitter.com/Hana_INFP/status/1516618874027880450
所以这些怎么说？

**Comment by tomieric** [comment]
**天下乌鸦一样黑**，你能出国就出国（最好有足够的钱，没钱免不了要当狗腿子），这是这个纲领里面所说的迁徙自由，不必搞这些思想洗脑。

无论去到哪个地方，都是会受到当地的限制级文化约束。

比如去到美丽国，无可避免的枪支，种族，尤其是对华人仇恨（具体大概也是外媒一直渲染布尔什维克是邪恶的，说天朝到处是人吃人，如果是这样的话，你现在还能愉愉快快在这上网），你顶着黄皮肤估计是不可避免的。

大多数人会选择华人占多的国家抱团，比如新加坡🇸🇬。

**Comment by qiujunhan** [comment]
> > 天要下雨，娘要嫁人。不爱国的想跑的就让他们跑呗，咱也不稀罕。
> > 中国特色社会主义是改革开放以来中国共产党的全部理论和实践的主题，是党和人民历尽千辛万苦、付出巨大代价取得的根本成就。中国特色社会主义最本质的特征就是中国共产党的领导，中国共产党始终代表中国最广泛人民群众的利益。
> 
> 爱中华民族 ≠ 爱国 ≠ 爱中国共产党，请分清楚这一概念
> 
> https://twitter.com/Hana_INFP/status/1516617636351594499 https://twitter.com/Hana_INFP/status/1516618874027880450 所以这些怎么说？

我的评价是：傻逼

**Comment by jiayouba233** [comment]
> > > 天要下雨，娘要嫁人。不爱国的想跑的就让他们跑呗，咱也不稀罕。
> > > 中国特色社会主义是改革开放以来中国共产党的全部理论和实践的主题，是党和人民历尽千辛万苦、付出巨大代价取得的根本成就。中国特色社会主义最本质的特征就是中国共产党的领导，中国共产党始终代表中国最广泛人民群众的利益。
> > 
> > 
> > 爱中华民族 ≠ 爱国 ≠ 爱中国共产党，请分清楚这一概念
> > https://twitter.com/Hana_INFP/status/1516617636351594499 https://twitter.com/Hana_INFP/status/1516618874027880450 所以这些怎么说？
> 
> 我的评价是：傻逼

原来就是来骂人的啊（

不知道您对 四月之声 这部短小的视频怎么看？不知道您对这个片子遭到全网和谐又怎么看呢？
要求全网和谐的人估计也是党员吧，这代表了最广泛人民群众的利益吗？
