### ISSUE TITLE
Never see such a political repo in github

### ISSUE THREAD

**Issue by ZhuGeRoastedFish** [The-Run-Philosophy-Organization/run#217]
Reading these issues just like reading those political arguments in twitter and youtube, full of discrimination and hate.
Please make github clean & pure, it should be a code repo here! Thousands of developers sharing their projects in github, ignoring the nationality, or whatever about politics...

**Comment by laijiawei** [comment]
If you dont like this repo,please ignore it. This project has 9.1K star,it shows that many people need this project. I like this project because it helps me seek freedom more easily.By the way ,the project has nothing to do with politics.

**Comment by sgfcz** [comment]
少jb装外宾嗷
