### ISSUE TITLE
狗屁不通，以短短百年的科技繁荣强行解释其制度的优越性

### ISSUE THREAD

**Issue by SmallComfort** [The-Run-Philosophy-Organization/run#230]
等20年后中国科技超越西方，到时候润出去的你，是不是会发一篇怎么润回来的高论呢？

**Comment by Himself65** [comment]
Closing as you have win

**Comment by nightire** [comment]
@SmallComfort 兄弟不必生气，几千年的历史长河中，像这种狗腿子“人才”咱还见得少吗？

为了追求更好的工作、生活环境而选择出国留洋乃至定居这都可以理解，因为这属于个人的选择；哪怕你为了一些原因自愿放弃中国国籍加入它国国籍那也是你的自由——法律并不禁止。这些个人的言行并没有节操上的硬伤，还是可以当人去对待的。

但是一些狗腿子就不同了，出国不好好出国，非要打着“现在的国家哪里哪里不好”的幌子来宣扬自己的“出逃理念”。表面上似乎是在交流出国求学或工作的经验心得，实际上却是在接着这个机会反复给大家洗脑，无非就是想要建立一种错误的因果关系：**我出国不是因为我要追求更好，而是因为我现在待的国家不好。**

没关系的，狗腿子可以费尽心机创建所谓的“润学派”，因为它们心虚所以不敢明目张胆的谈出逃（run），才会拐弯抹角的琢磨出个“借拼音之名，行洋片之实”来。但是对付狗腿子就简单直接的多了，你只需要对它们说一个字：gun！

**Comment by Bian-Sh** [comment]
> @SmallComfort 兄弟不必生气，几千年的历史长河中，像这种狗腿子“人才”咱还见得少吗？
> 
> 为了追求更好的工作、生活环境而选择出国留洋乃至定居这都可以理解，因为这属于个人的选择；哪怕你为了一些原因自愿放弃中国国籍加入它国国籍那也是你的自由——法律并不禁止。这些个人的言行并没有节操上的硬伤，还是可以当人去对待的。
> 
> 但是一些狗腿子就不同了，出国不好好出国，非要打着“现在的国家哪里哪里不好”的幌子来宣扬自己的“出逃理念”。表面上似乎是在交流出国求学或工作的经验心得，实际上却是在接着这个机会反复给大家洗脑，无非就是想要建立一种错误的因果关系：**我出国不是因为我要追求更好，而是因为我现在待的国家不好。**
> 
> 没关系的，狗腿子可以费尽心机创建所谓的“润学派”，因为它们心虚所以不敢明目张胆的谈出逃（run），才会拐弯抹角的琢磨出个“借拼音之名，行洋片之实”来。但是对付狗腿子就简单直接的多了，你只需要对它们说一个字：gun！

纵有万般不好，中华民族”落叶归根“的思想是刻在骨子里面的，现在不好，但是能有以前差吗？
我们要以发展的眼光看待
况且任何地方都逃不了资本的操弄
没有国家调控
国内资本早就该被美元一轮又一轮的吃干抹净咯，个人愚见哈

**Comment by qiujunhan** [comment]
> 等20年后中国科技超越西方，到时候润出去的你，是不是会发一篇怎么润回来的高论呢？

美国给钱办事的狗腿子罢了

**Comment by Meritamen** [comment]
CHINK
