### ISSUE TITLE
建议新加一个folder

### ISSUE THREAD

**Issue by charchar114514** [The-Run-Philosophy-Organization/run#237]
里面分别建立各个国家的folder
用于搜集全球各国的政策，以及润所需要的条件

**Comment by charchar114514** [comment]
https://www.zhihu.com/question/487540745/answer/2397165468

毕竟除了美加澳以外还有不少其他国家

**Comment by the-run-philosophy** [comment]
是有的，比如这个：https://github.com/The-Run-Philosophy-Organization/run/tree/main/%E6%B6%A6%E5%AD%A6%E6%96%B9%E6%B3%95%E8%AE%BA/%E5%90%84%E5%9B%BD%E9%80%89%E6%8B%A9

**Comment by the-run-philosophy** [comment]
@charchar114514 你可以在这个文件夹里添加新的国家。

**Comment by the-run-philosophy** [comment]
不过可以的话，是否可以联系这些作者来github？

**Comment by stackunderflow111** [comment]
> 不过可以的话，是否可以联系这些作者来github？

不是每个人都会用的。我记得我第一次学习git的时候适应了半天，总是搞不懂git add，git commit和git push

**Comment by the-run-philosophy** [comment]
你可以下载github desktop。然后一切都很简单了

**Comment by the-run-philosophy** [comment]
不需要记住这些命令；这些命令确实很烦
