### ISSUE TITLE
走好不送

### ISSUE THREAD

**Issue by hjforever** [The-Run-Philosophy-Organization/run#269]
期待你们能将润学在国外发扬光大，如果能成为一门宗教就更好了。但是不要回中国了，我们这里配不上你们这些人才。走好不送。润字最好改下。

**Comment by hanayashiki** [comment]
国内虽然有各种各样的问题，但总体来说机会还是国内多！

**Comment by jasonyuan-cn** [comment]
真的神烦这些阴阳人，好好的一个学技术地方，也要政治化。赶紧润赶紧的。

**Comment by bosskwei** [comment]
我们都润了以后，以后建设祖国就靠你们三本大专人上人了

**Comment by jasonyuan-cn** [comment]
> 我们都润了，以后建设祖国就靠你们三本大专人上人了

哈哈，我们不仅有三本，我们还有大专生哦，我们会好好建设我们的祖国的，你们要好好舔好屁眼，不过舔再干净今天俄罗斯耗材的事情明天也会发生在你们身上哦

**Comment by zhinatu** [comment]
> 
六亿月收入不到一千的才叫耗材吧，之前南海p30坠机死的农村穷丘八耗材种种的耗材🤣

**Comment by zhinatu** [comment]
> 

六亿月收入不到一千的才叫耗材吧，之前南海p30坠机死的农村穷丘八耗材种种的耗材

**Comment by zhinatu** [comment]
俺润了但家人还在拆那挣钱哦😅

**Comment by bosskwei** [comment]
> 

这个小伙子一看气色就知道是年薪百万纳税千万

**Comment by bosskwei** [comment]
> > 俺润了但家人还在拆那挣钱哦sweat_smile
> 
> 你看看，阴阳人不以不忠不孝为耻，还搁着炫耀呢。按理说，你爹娘能在中国挣钱供你出国留学，也算是他们那代人的人中龙凤了，为啥会养出一个你这种不忠不孝，不知廉耻的废物来呢。你爹娘为了在国内应该做了不少铺垫吧，就当废物的润了？你说那些靠自身读书拼搏出来的人，可能被糖衣炮弹吸引到国外去，我还能理解。但是你这种家境好，又润的人，我只能想到一种可能，就是自己眼高手低，觉得自己怀才不遇，只有你们白皮爹能欣赏你，其实自己就是一个废物。话说回来，你爹娘知道你的言语和思想吗？


这个小伙子一看气色就知道是年薪百万纳税千万

**Comment by hjforever** [comment]
> 我们都润了，以后建设祖国就靠你们三本大专人上人了

我希望你要抓紧润学(叫润教更合适)的宗旨，像你这样的羊确实不适合建设祖国，去国外会过的好一点。

**Comment by zhinatu** [comment]
> > 俺润了但家人还在拆那挣钱哦😅
> 
> 你看看，阴阳人不以不忠不孝为耻，还搁着炫耀呢。按理说，你爹娘能在中国挣钱供你出国留学，也算是他们那代人的人中龙凤了，为啥会养出一个你这种不忠不孝，不知廉耻的废物来呢。你爹娘为了在国内应该做了不少铺垫吧，就当废物的润了？你说那些靠自身读书拼搏出来的人，可能被糖衣炮弹吸引到国外去，我还能理解。但是你这种家境好，又润的人，我只能想到一种可能，就是自己眼高手低，觉得自己怀才不遇，只有你们白皮爹能欣赏你，其实自己就是一个废物。话说回来，你爹娘知道你的言语和思想吗？
看这急的😅， 哪呆着舒服润哪儿，伟大复兴习思想也就骗骗耗材

**Comment by bosskwei** [comment]
> > 我们都润了，以后建设祖国就靠你们三本大专人上人了
> 
> 我希望你要抓紧润学(叫润教更合适)的宗旨，像你这样的羊确实不适合建设祖国，去国外会过的好一点。

你说的对，我是手握 passport 的羊，你是在总书记亲自指导指导下努力建设社会主义事业的人

**Comment by bosskwei** [comment]
小学生亲自指导大专人上人赶英超美
![FAVgvDwVQAYPPU3](https://user-images.githubusercontent.com/12762888/165422968-01597d81-c266-4a30-9883-f63ef7f852ba.jpeg)

**Comment by jasonyuan-cn** [comment]
> > > 俺润了但家人还在拆那挣钱哦😅
> > 
> > 
> > 你看看，阴阳人不以不忠不孝为耻，还搁着炫耀呢。按理说，你爹娘能在中国挣钱供你出国留学，也算是他们那代人的人中龙凤了，为啥会养出一个你这种不忠不孝，不知廉耻的废物来呢。你爹娘为了在国内应该做了不少铺垫吧，就当废物的润了？你说那些靠自身读书拼搏出来的人，可能被糖衣炮弹吸引到国外去，我还能理解。但是你这种家境好，又润的人，我只能想到一种可能，就是自己眼高手低，觉得自己怀才不遇，只有你们白皮爹能欣赏你，其实自己就是一个废物。话说回来，你爹娘知道你的言语和思想吗？
> > 看这急的😅， 哪呆着舒服润哪儿，伟大复兴习思想也就骗骗耗材

我又不是你爹，我急啥，你自己舒服就好，大地母亲祝福你
