### ISSUE TITLE
要润就好好润 别润之前还得踩上一脚

### ISSUE THREAD

**Issue by Cinichengbuweikong** [The-Run-Philosophy-Organization/run#277]
中国做的不好 你打算润 那你润就完了呗 不管咋的 中国还是一口一口饭把你养成了这么大 至少把你养活了 但他对你不好 那你就润呗 
对你不好也不期望你能感激 但你润之前还踩上一脚? 
那小猫小狗离家之前也没说要咬主人一口再走啊 一个人连小猫小狗的觉悟都没有?
作为一个教如何润的仓库 不多搜集一些如何润的信息 就在这里扯没用的 能来这个仓库的都知道中国哪里做的不好 不用再一遍一遍强调
如此激进地捧一踩一 虽然我们我认同你2/3以上的中国做的烂的地方 但在这个仓库中 很难不让人认为是别有所图
要润就好好润 要教人润就好好教人润 别润之前还要踩上一脚 不至于 不至于

**Comment by taobowen** [comment]
当狗就好好当狗，别叫之前还咬上别人一口，不至于不至于

**Comment by Tipeman** [comment]
点进来的都是抱有精准目的的，你点进来要不就是想run，要不就是想来吐口痰，说一大堆有什么意思呢？感觉很好会润吗？没有矛盾润个屁呢
