### ISSUE TITLE
提个建议，可以将国内的各一本二本三本飞跃计划/飞跃手册中关于润关于申请的内容放进来

### ISSUE THREAD

**Issue by cafferychen777** [The-Run-Philosophy-Organization/run#30]
例如
2020届东南大学飞跃计划https://www.yuque.com/2020seufly/guide

南方科技大学飞跃手册https://sustech-application.com/#/?id=%e5%8d%97%e6%96%b9%e7%a7%91%e6%8a%80%e5%a4%a7%e5%ad%a6%e9%a3%9e%e8%b7%83%e6%89%8b%e5%86%8c

上海交通大学生存手册https://survivesjtu.gitbook.io/survivesjtumanual/

华科EE系飞跃计划https://hongyili.net/attaches/%E5%8D%8E%E4%B8%AD%E5%A4%A7%E7%94%B5%E6%B0%94%E9%A3%9E%E8%B7%83%E6%89%8B%E5%86%8C.pdf

华科光电飞跃计划https://hust-feiyue.github.io/2020_feiyue.pdf

**Comment by the-run-philosophy** [comment]
赞

**Comment by chan1919** [comment]
iidesune
