### ISSUE TITLE
《没钱人如何移民澳洲.md》有一个错误。417不支持中国人，462才支持中国人。请更正。

### ISSUE THREAD

**Issue by yjfvictor** [The-Run-Philosophy-Organization/run#307]
[没钱人如何移民澳洲.md](https://github.com/The-Run-Philosophy-Organization/run/blob/main/%E6%B6%A6%E5%AD%A6%E6%96%B9%E6%B3%95%E8%AE%BA/%E5%90%84%E5%9B%BD%E9%80%89%E6%8B%A9/%E4%BA%9A%E6%B4%B2%E5%92%8C%E5%A4%A7%E6%B4%8B%E6%B4%B2/%E6%BE%B3%E5%A4%A7%E5%88%A9%E4%BA%9A/%E6%B2%A1%E9%92%B1%E4%BA%BA%E5%A6%82%E4%BD%95%E7%A7%BB%E6%B0%91%E6%BE%B3%E6%B4%B2.md) 有一个错误，给出了 [Working Holiday visa (Subclass 417)](https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417) ，但是这个417签证是不支持中国护照持有者的。支持中国护照持有者的签证是 [Work and Holiday (Subclass 462)](https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-462)。

417签证的条件： https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-417/first-working-holiday-417#Eligibility
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/6044012/166181786-c2cf8277-a5ba-4214-8baf-184ceb9934a2.png">

462签证的条件： https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/work-holiday-462/first-work-holiday-462#Eligibility
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/6044012/166181811-817a54c0-a7fa-4b6a-8876-c42de0f4be0a.png">

此外，澳洲驻华大使馆一个专门针对中国人的462签证的说明页面：
英文版： https://china.embassy.gov.au/bjng/workandholidaysc462faq.html
中文版： https://china.embassy.gov.au/bjngchinese/WorkandHolidaysc462FAQcn.html

**Comment by the-run-philosophy** [comment]
可否提交pr？

**Comment by the-run-philosophy** [comment]
fixed
