### ISSUE TITLE
Tracking issue for adding automatic Web Archive saver in CI

### ISSUE THREAD

**Issue by jiayouba233** [The-Run-Philosophy-Organization/run#313]
#312 在此PR中我提交了一个yml让其检查所有的MarkDown文件中的链接，检查其是否可以访问

但遇到了像 一亩三分地这样走Cloudflare的会返回错误（正常的状态应该是200）

**Comment by jiayouba233** [comment]
需要一个CI，CI能增量检查markdown里的链接是否有近期web archive存档

**Comment by the-run-philosophy** [comment]
@jiayouba233 需要增加ci吗

**Comment by jiayouba233** [comment]
> @jiayouba233 需要增加ci吗

我是认为需要的：一方面也能检查MarkDown中提供的链接是否正确，另一方面也能链接外部链接是否有效

我打算向上游发个Issue

**Comment by jiayouba233** [comment]
上游Issue：https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/138
