### ISSUE TITLE
美国枪击案又死了18个儿童

### ISSUE THREAD

**Issue by trillionstar07** [The-Run-Philosophy-Organization/run#417]
现在都不公开监控，绝对不要信，我的一个美国朋友说至少是官方公布数字的十倍
我一美国朋友给我说，救护车来了几百辆，整个州的血库都用完了，政府立马组织美国大兵献血，献血的大兵排队长度可以绕地球3周

**Comment by TrustDec** [comment]
我美国盆友说死了108个

**Comment by xyzhou-1** [comment]
Fake news,next
