### ISSUE TITLE
没抽到H1B怎么办

### ISSUE THREAD

**Issue by djm-xjtu** [The-Run-Philosophy-Organization/run#43]
如题

**Comment by Luckyfisher-Yu** [comment]
加拿大欢迎你。美国大公司relocate温哥华。5年内入籍

**Comment by the-run-philosophy** [comment]
参考L1
找一个公司拿Day1 CPT
都可以

**Comment by the-run-philosophy** [comment]
参考这个md：

https://github.com/The-Run-Philosophy-Organization/run/blob/main/%E6%B6%A6%E5%AD%A6%E6%96%B9%E6%B3%95%E8%AE%BA/%E5%90%84%E5%9B%BD%E9%80%89%E6%8B%A9/%E7%BE%8E%E5%9B%BD/%E6%B2%A1%E6%8A%BD%E5%88%B0H1B%E6%80%8E%E4%B9%88%E5%8A%9E.md
