### ISSUE TITLE
西班牙50w欧黄金移民和非盈利移民，成本不高

### ISSUE THREAD

**Issue by aeolod998** [The-Run-Philosophy-Organization/run#44]
1+2+2满五年后可换西5年长居，可再申请欧洲居留卡。
50w欧必须投资住宅，满5年后可出出售。一般买几套出租，基本已经够每月花销，当然要费点心收拾。
非盈利成本最低，自己DIY花费在1-2wRMB左右。以一家三口为例，稳妥的话能出示150W左右RMB合法资产相关证明即可申请通过，不需要提前转帐海外，不需要提前买房。帝都领区好通过，别的领区会要求再多些和严格些。

**Comment by the-run-philosophy** [comment]
讨论不要提issue，请提交pr或去讨论区
