### ISSUE TITLE
网站域名问题

### ISSUE THREAD

**Issue by Himself65** [The-Run-Philosophy-Organization/run#45]
暂时使用gitbook进行部署，gitbook不支持Apex domain，正在寻找其他替代方式

问题复现：https://www.runoutfor.life 可以访问，但是 https://runoutfor.life 不可以访问

**Comment by the-run-philosophy** [comment]
@Himself65 现在解决了？

**Comment by Himself65** [comment]
not yet

**Comment by Himself65** [comment]
Still waiting for [Netlify's open-source license](https://www.netlify.com/open-source/). If not be approved, I will try another way

**Comment by the-run-philosophy** [comment]
thanks

**Comment by Himself65** [comment]
good news, [netlify](https://www.netlify.com/) will sponsor us free deploy for the project
