### ISSUE TITLE
希望有更多润东亚的实例

### ISSUE THREAD

**Issue by FatPudge** [The-Run-Philosophy-Organization/run#455]
润日，润台，润韩，甚至润越南，再不济地润港澳（这两个地方我无限看坏）。汉字文化圈可能更适合我一些。

**Comment by Alex-Jee** [comment]
润台别想了，根本不可能，真以为人家把大陆的当同胞？全世界防大陆人最严的就是台。润韩干啥？韩国人自己都在大批向欧美移民，嫌不够卷吗？另外，韩国朝鲜未来必有一战，难道到时候你再往外跑？

**Comment by the-run-philosophy** [comment]
增加了润日本

**Comment by FatPudge** [comment]
谢谢，希望能删除这个issue
