### ISSUE TITLE
之前国外疫情严重的时候想着法往国内跑，现在国内疫情严重了就想着run？？？

### ISSUE THREAD

**Issue by CruxCv** [The-Run-Philosophy-Organization/run#50]

**Comment by christorange** [comment]
lmao, someone who cannot even get a passport now is really pissed off🤣

**Comment by the-run-philosophy** [comment]
没有护照

**Comment by CruxCv** [comment]
心虚？

**Comment by CruxCv** [comment]
在你们眼里，没run 等于 没护照。魔怔了

**Comment by christorange** [comment]
你真的很有意思，别人开个repo自己分享信息自娱自乐，也没辱你大支那国，你跑过来犯什么贱，it's none of your business, 管好你自己😅

**Comment by CruxCv** [comment]
> 你真的很有意思，别人开个repo自己分享信息自娱自乐，也没辱你大支那国，你跑过来犯什么贱，it's none of your business, 管好你自己😅

笑死，我看到了就想喷两句，怎么，不让说？我管好了我自己，然后就想管管墙头草🤪
