### ISSUE TITLE
此仓库有贪天之功的嫌疑，擅自代表所有润人。推荐一个女性润学仓库链接，欢迎润女阅读和参与重建，反对男本位窃取整个润学概念

### ISSUE THREAD

**Issue by FemRun** [The-Run-Philosophy-Organization/run#501]
某些人，借润还魂，企图窃取全部润学果实。
完全隐藏了润女的贡献。
**个别润男，自诩润学官方，利用模因污染，将整个润学据为己有，挪用他人输出，擅自代表所有润人。**  绑架其余润人到他的话语权之下。
**借润学之名吞噬他人贡献，忽略和消除异己，瓦解其余润学流派，严重损害润学本体。**

**散落各平台的润女，不应该坐视话语权被夺走。**
**润女拒绝承认男本位为润学**
https://github.com/FemRun/FemRun

您的润学，是虚假的润学。
**除非，**
**你把FemRun，merge进来**

--------

答某蝻问：
我们**提交PR之后，没有动静，有被骗fork的危险**，暂时删除了已提交的部分。我们仓库是公开的，所有人可以看到目前的全貌。
提醒大家，不要继续上当，只要某些人一直装死，就可以一直白嫖你的关注。你贡献了他就装死，你删除了他就阴阳怪气贬低你，对你打疲劳战。我们不可能无限度纵容某些人。在对方明确表示接受，保证通过merge之前，不要草率贡献流量。实在想fork，可以新建私有空仓库，把目标仓库import进来，删除你fork的公开仓库。
**我们注意到，已有其他merge放在那里没动。一些很好的建议他们并不采纳**。怀疑此仓库，是草船借箭的草船，表面没有得到有效管理，其目的并不真诚，如上所述，危害真正的润学。
**更可笑的是，某蝻您自己，也需要向您跪舔着的所谓“太祖”，乞讨权限，等他翻牌子。您把他舔爽没有啊**

------

为防止其他润学流派，在仓库作者的迫害下走失，请点击并记住我们FemRun的链接，以备不时之需，共同反抗，商讨对策。

不要阴阳怪气或者装死。我们要一个正面保证。
**最后问一遍，您到底，mer不merge。**

------

没必要客气了。骗大家fork。冒充官方，自封领袖，架子倒不小。
都是猫猫狗狗就他装大尾巴狼。即便逐鹿中原哪里轮得到他。
他自己兜里一滴真正有用价值都不漏，扔垃圾情绪，**忽悠大家给他注资，拉人下水。**
他算哪棵葱，自封太祖。趁机做我们的大爹。
还没得到实质价值，没润出个所以然，先被他骗，认起爹，供起祖宗来了。难道我们润，就为了便宜他。替他扛旗忽悠，
**奴性这么强烈，去哪里都先捧出个主子。**
即便你另有野心，但凡知道这个货底细，就清楚这里面，压根没有小爹给你做。
**卖了你帮他数钱。** 与其被他利用，还不如另拜山头，另起炉灶。
我们润人，才不为虎作伥，打的就是这种大爹。

-------

答粉红蝻问：
笑死。你就是来自臭名昭著的apachecn，指望它壮胆。
你们未经允许**群发骚扰邮件。教男生做人渣，教幼稚园水平pua。擅自打着别人技术工具官方的旗号，忽悠不明真相的用户，靠冒充官方骗流量起家。** 专业水平跟做人水平，一样臭。下三滥招术。
你一个小粉红软件用户，凑什么热闹。我们Femrun仓库推荐的蓝鸟，reddit链接，你都不会访问？
好心劝劝你，既然润，趁早悔过自新。润人可不吃你这套，当心人家给你处私刑，上极刑。在GitHub搞男权，还没找你算账。也只有粉红洼地lv，忍你这种蝻。洼地蝻就这两下子还敢润。越学越完蛋。润到火星都改不掉蝻本色。
脑子进了什么液体，想不开来惹润女。越是土鳖越爱装洋，爹味傻得可怜。你㿟爹都看不起你。
真是笑料。果然，你们自封大爹，冒充官方，成员就这种货色。乐

**Comment by ysinsane** [comment]
What is your problem? Who's ever said anything about gender?

**Comment by padresvater** [comment]
你戏还挺多，成功把我逗乐了

**Comment by jiayouba233** [comment]
那您倒是提交 Pull requests 啊？
不会连 PR 都不会交吧（

**Comment by Tandoy** [comment]
Dirty practices for u.BTW If you want to provoke Gender Antagonism, please visit Weibo where you want.8D

**Comment by xxx-zzl** [comment]
好  打起来

**Comment by lightingLion** [comment]
b豆［给心心］

润太祖 ***@***.***> 于 2022年8月20日周六 11:59写道：
