### ISSUE TITLE
再次申请收录我们的仓库，将两篇文章链接放入readme

### ISSUE THREAD

**Issue by FemRun** [The-Run-Philosophy-Organization/run#508]
文章链接
https://github.com/FemRun/FemRun/blob/main/%E7%B2%BE%E8%AE%B2%E3%80%8A%E6%89%8B%E6%8A%8A%E6%89%8B%E6%95%99%E9%94%81%E7%94%B7%E6%90%AC%E8%BF%90%E3%80%8B.md
https://github.com/FemRun/FemRun/blob/main/%E8%A2%AB%E3%80%8A%E6%89%8B%E6%8A%8A%E6%89%8B%E6%95%99%E7%90%90%E7%94%B7%E6%90%AC%E8%BF%90%E3%80%8B%E8%B4%AC%E6%8D%9F%E7%9A%84%E5%A5%B3%E6%80%A7%E7%BE%A4%E4%BD%93.md

申请收录FemRun https://github.com/FemRun/FemRun
润女港湾仓库，就不做要求了。推荐移步，欢迎阅读 https://github.com/FemRun/FeministCN

**Comment by jiayouba233** [comment]
请自行提交 Pull requests，所有的 Check 通过后 @the-run-philosophy 会 Merge 进来的（
这是参与此仓库的基本要求 ...

**Comment by jiayouba233** [comment]
这个仓库似乎只有 ta 和 @himself_65 有权限 Merge，骗 fork 有没有钱 ...

不过还是建议您先提交个 Pull requests 试试（

**Comment by jiayouba233** [comment]
> > 这个仓库似乎只有 ta 和 @himself_65 有权限 Merge，骗 fork 有没有钱 ... 不过还是建议您先提交个 Pull requests 试试（
> 
> 好的。没小钱，但是有别的东西。该给点击star的真实用户结算报酬才对。 麻烦您帮忙广而告之，他这种大爹蝻，有可能即将被剪刀剪碎

但是 Star 本身应该算是给仓库主的鼓励的（？
而且 Github 上 Star 数比这个仓库多的还有不少 ...

**Comment by the-run-philosophy** [comment]
我在啊？
