### ISSUE TITLE
为什么不添加其他学校手册。亡浙大之心不死

### ISSUE THREAD

**Issue by Ocean9** [The-Run-Philosophy-Organization/run#511]
是别的学校不配吗。仓库其他作者的学校不配吗。
人家手册主编做出来的工作，扎根内陆主流高校，不可能同意授权他挪用，掐断自己潜在的发展机会。
即使万一也有一个，擅长演讲，口才出众，芳名远播的父亲。看起来，人家没打算，跟主流彻底反目。不可能让某人把他拖下水，抹上排泄物。像他那样一闹把亲爹的演讲驳倒。
就算人有意向，何必屈尊，无偿参加一个势利小人，模拟的造反游戏。干嘛不直接自己举旗。
对他的母校——当然他不承认这个前任或者说旧妈，只认他的美国学校——小人得志过河拆桥。可不像别的校友，光嘴上黑，他真心盼它死。反正翅膀硬了，他再也用不上浙大了。
那他为什么，不去挪用最喜欢的，清华的手册。
莫非，清华人不同意让他利用，拒绝被他将军逼宫，被他骗交投名状，不舔他，不让他把排泄物，抹到头上。
得罪清华人会带来难堪。怕清华排斥他。

**Comment by jiayouba233** [comment]
作为此项目的贡献者之一，这些手册似乎是 bboceng 在公开互联网上找到的

在 [#460](https://github.com/The-Run-Philosophy-Organization/run/issues/460) 已经有人提出异议，然后我在随后提交了 Pull requests 将这些飞跃手册移除了（
现在此仓库无法直接查看到相关学校的飞跃手册
