### ISSUE TITLE
格局太低了！！！

### ISSUE THREAD

**Issue by douyw** [The-Run-Philosophy-Organization/run#526]
简单说几句。

“润”——藏头露尾，非君子所为。如果一定要用，那有个词语大家一定听说过：“润之”。不妨改改，按语境也说的过去。:-)

这里所谓的“润”，大概就是自己跑路的意思，跑到自己所向往的他乡。如果你心里只有你自己，那就跑好了。

13多亿人口，不可能都跑路，跑路的也只是小小的一撮，与13亿人比起来可以忽略不记。让自己被外媒洗坏的脑子再多想一层：邻居打架旁边递刀子的家伙是个什么鬼！！！这个家伙就是你所向往的？？？

提高认知与格局，巨龙的腾飞无可阻挡！

**Comment by jiayouba233** [comment]
“邻居打架旁边递刀子”这应该指的是俄乌战争吧 ...
而且“外媒洗坏”请指出是哪个外媒的哪些报道 ... 而且按这种说法我是不是也可以说“被国内媒体洗坏的脑子再多想一层”？
没有哪个国家或制度是完美的，或许应该说是选择的问题（？

而且话说回来就目前国内这种言论环境，崛起真的是个好事吗 ...

**Comment by PreWisdom** [comment]
玩文字狱是吧，还有高明点的手段吗

**Comment by JohnHenryEden** [comment]
没人逼你非得跑，你如果在洼地如鱼得水，那祝福你

**Comment by JohnHenryEden** [comment]
This is an automatic reply, your message has been received.I will read and reply the e-mail ASAP, sorry for any inconvience.黄靖珩，Huang Jingheng
