### ISSUE TITLE
 这个仓库和隔壁`chinese-poetry`一起在周榜上，莫名有种奇异而无法言表之感

### ISSUE THREAD

**Issue by meiziRain** [The-Run-Philosophy-Organization/run#544]
![image](https://user-images.githubusercontent.com/41403880/187120069-134feadc-c5c5-442f-8d19-5b285a6558cf.png)

一边是和代码毫无关系的魔怔政治痴儿；
一边是为古籍集成数据库群策群力的后辈；
真是鲜明的表达了人各有志。

把哪里当做家，与政治无关，真能去他们应许之地的人，我祝福他们收获自己的幸福与安宁，

但一想到这其中绝大多数的人，依然要和我这样被洗脑的羔羊一起在油锅中饱受煎熬，愚钝的我感知不到的痛苦却让
清醒的它们在人间炼狱中承受了，看它们拉扯灵魂求而不得在GitHub抱团取暖失魂落魄的样子，我的确泪目了。

众生是羔羊，上帝是牧羊人，也许真正的羔羊注定要离它们God更近一些吧。

**Comment by hEzoooo** [comment]
一边是和代码毫无关系的魔怔封建文化复辟痴儿；
一边是为了美好生活而群策群力的后辈；
真是鲜明的表达了人各有志。

**Comment by meiziRain** [comment]
润哥就这啊，属实是学渣一个连封建文化都学不好，只能拙劣地模仿吧，一如写的代码只能抄抄改改😊。


话说汉字也是封建残余，建议用英语互动捏😋



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月30日(周二) 晚上8:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [The-Run-Philosophy-Organization/run]  这个仓库和隔壁`chinese-poetry`一起在周榜上，莫名有种奇异而无法言表之感 (Issue #544)




 
一边是和代码毫无关系的魔怔封建文化复辟痴儿；
 一边是为了美好生活而群策群力的后辈；
 真是鲜明的表达了人各有志。

**Comment by meiziRain** [comment]
润哥删啥呢？主子这么丢脸在分享技术的地方弄这些有的没的，徒子徒孙这点斗志都没有？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月30日(周二) 晚上8:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [The-Run-Philosophy-Organization/run]  这个仓库和隔壁`chinese-poetry`一起在周榜上，莫名有种奇异而无法言表之感 (Issue #544)




 
一边是和代码毫无关系的魔怔封建文化复辟痴儿；
 一边是为了美好生活而群策群力的后辈；
 真是鲜明的表达了人各有志。
