### ISSUE TITLE
10043限制清单

### ISSUE THREAD

**Issue by Yukang-LIAN** [The-Run-Philosophy-Organization/run#56]
建议增加针对10043限制名单高校的润美方法

**Comment by the-run-philosophy** [comment]
cc @lidangzzz

**Comment by stackunderflow111** [comment]
没有，没有，没有
建议转润加拿大

**Comment by Yukang-LIAN** [comment]
> 没有，没有，没有 建议转润加拿大

先润加拿大 再南下美利坚也是一种方法嘛

**Comment by the-run-philosophy** [comment]
已添加 https://github.com/The-Run-Philosophy-Organization/run/blob/main/%E6%B6%A6%E5%AD%A6%E5%AE%9E%E4%BE%8B/%E8%AE%A1%E7%AE%97%E6%9C%BA/%E4%B8%80%E4%BA%9B%E5%B8%B8%E8%A7%81%E7%9A%84%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%8E%BB%E7%BE%8E%E5%9B%BD%E9%97%AE%E9%A2%98%E6%80%BB%E7%BB%93.md
