### ISSUE TITLE
那个北美润学群是你们搞的吗？感觉不是很靠谱的样子

### ISSUE THREAD

**Issue by xsw0** [The-Run-Philosophy-Organization/run#57]

**Comment by xsw0** [comment]
是不是利用你们影响力搞事情的

**Comment by xsw0** [comment]
> 你是指哪个群？官方群只有README.md里面的两个
![Uploading Screen Shot 2022-04-15 at 1.07.00 AM.png…]()
<img width="339" alt="Screen Shot 2022-04-15 at 1 09 19 AM" src="https://user-images.githubusercontent.com/66742822/163439161-17e881a9-1d4c-4532-ae89-a2a18ee5cb56.png">
https://t.me/+isQZU2rU5TA5MWYx

**Comment by Himself65** [comment]
> > 你是指哪个群？官方群只有README.md里面的两个
> 
> <img alt="Screen Shot 2022-04-15 at 1 07 00 AM" width="434" src="https://user-images.githubusercontent.com/66742822/163439263-89f9a70b-6ae0-4b4c-8c70-3e28b8a3b8a3.png">
> 
> <img alt="Screen Shot 2022-04-15 at 1 09 19 AM" width="339" src="https://user-images.githubusercontent.com/66742822/163439161-17e881a9-1d4c-4532-ae89-a2a18ee5cb56.png">
> 
> https://t.me/+isQZU2rU5TA5MWYx

不是

**Comment by Himself65** [comment]
防止被骗应该是自己的义务，我们（项目团队成员）不是幼儿园老师
