### ISSUE TITLE
义演丁真，鉴定为纯纯的轮子

### ISSUE THREAD

**Issue by TensorABC** [The-Run-Philosophy-Organization/run#610]
1，不是东欧那一波搞所谓“民主的社会主义”的自由派
2，不是庸俗主义的奥派
因而鉴定为纯纯的没有脑子的邪教
先close issues禁止讨论，然后你还要在我下面留言反驳我，GitHub的环境这么好这么就来了你们这一帮轮子！MLGB不然我还需要梯子访问Github？？？

**Comment by Reviona** [comment]
好好好嗯嗯嗯

**Comment by talmudmaster** [comment]
哈哈哈哈哈哈哈

**Comment by xmoli** [comment]
确实

**Comment by cultivater** [comment]
原批能不能收收味？

**Comment by huhumeng2** [comment]
啊对对对

**Comment by Miooiio** [comment]
差不多得了

**Comment by TensorABC** [comment]
我反正是能上网捏

yupeishan ***@***.***> 于2022年11月29日周二 12:05写道：
