### ISSUE TITLE
征求润学LOGO

### ISSUE THREAD

**Issue by the-run-philosophy** [The-Run-Philosophy-Organization/run#62]

**Comment by An0th3r** [comment]
不如直接用华润的logo

**Comment by GaaiLam** [comment]
![图片](https://user-images.githubusercontent.com/43839316/163529690-c45bf3be-d7e0-49ec-8dc7-edc4861350eb.png)

**Comment by hhstore** [comment]
- 这是我自制的. 拿走不谢. 😄
- https://github.com/better-run/run
- 喜欢的, 随便用


<h3  align="center">
    <img width="360" align="center" alt="run" src="https://user-images.githubusercontent.com/3252130/163540627-1f9b872e-f5b0-4b1a-94b0-bdc3ac69118d.png">
</h3>

**Comment by the-run-philosophy** [comment]
@hhstore  可以引用/收录你的 [README.md](https://github.com/better-run/run#readme) 么？

**Comment by tianyalang** [comment]
![68e224da473a99723a7b2085e78e4be9](https://user-images.githubusercontent.com/44080909/163623089-facaaef5-bdc6-4f07-bef5-3f53bdb49a16.jpeg)

**Comment by hhstore** [comment]
> 

- 可以啊. 
- 不过, 我有个问题. discord 群, 为啥 T 我? 我发了个 discord 群邀请链接. 而且我上面这个 repo, 也推荐了你们群啊.
- 另外也注明了, 是链接互换啊?
- 我的 discord 群. 也是介绍大家怎么润的. 
- 也没任何沟通麽? 不让互换链接, 我可以删啊. 
- 还是有啥利益相关?

**Comment by hhstore** [comment]
> @hhstore 可以引用/收录你的 [README.md](https://github.com/better-run/run#readme) 么？

- 可以啊. 
- 不过, 我有个问题. discord 群, 为啥 T 我? 我发了个 discord 群邀请链接. 而且我上面这个 repo, 也推荐了你们群啊.
- 另外也注明了, 是链接互换啊?
- 我的 discord 群. 也是介绍大家怎么润的. 
- 也没任何沟通麽? 不让互换链接, 我可以删啊. 
- 还是有啥利益相关?

**Comment by the-run-philosophy** [comment]
@hhstore 已收录

**Comment by 2096779623** [comment]
![logo](https://user-images.githubusercontent.com/57583560/173220742-7237b98f-95df-47c1-b620-04c2b8fce21e.gif)
