### ISSUE TITLE
要滚就赶紧滚啊，去舔洋大人的屁眼最舒服了，外面的屎都是甜口的

### ISSUE THREAD

**Issue by zhaoliang0302** [The-Run-Philosophy-Organization/run#633]

**Comment by z836454898** [comment]
不够你舔中共的官老爷的舒服😅

**Comment by zhaoliang0302** [comment]
> 不够你舔中共的官老爷的舒服😅

有钱有本事的想移民就移民了，穷逼才这在精打细算攻略，算到最后还不是窝在家里敲键盘

**Comment by zhaoliang0302** [comment]
> 总比你心甘情愿地被中共当人矿压榨好

哦，我没被压榨，看了你的star，我觉得你可能过得比较惨

**Comment by shinyypig** [comment]
<img width="1486" alt="image" src="https://github.com/The-Run-Philosophy-Organization/run/assets/30233673/23cd0ca0-050c-4732-bab0-30d6b904fbab">

唉，自己也不觉得扎眼。我要是说这种话，还一直留在网上每个人都看得到，想想都害臊哈。

**Comment by zhaoliang0302** [comment]
![Screenshot_20230721-121324__01](https://github.com/The-Run-Philosophy-Organization/run/assets/42333702/22d40f2e-8d2a-47da-a773-d241ed29d444)
怎么样，这样的长相美国爹收不收啊？

**Comment by bmphjhu906** [comment]
党员来了？

**Comment by tonyqus** [comment]
我看你也是搞数据分析、机器学习算法的，咋觉悟像是三线城市的。。。你学习的分类算法都是洋人发明的，你说为什么呢？我们国内的学术环境你心里没有数吗？

**Comment by vulcan2333** [comment]
哈哈哈哈哈哈它急了

**Comment by yinft** [comment]
666 这就急了？

**Comment by wizardforcel** [comment]
有本事年薪20万刀了再跟我比比

**Comment by zhaoliang0302** [comment]
> 有本事年薪20万刀了再跟我比比

🤣大路上比你收入高的多呢，你是不是见到高的都得跪下喊爹

**Comment by wizardforcel** [comment]
> > 万刀了再跟我比比
> 
> 🤣大路上比你收入高的多呢，你是不是见到高的都得

有吗？随便给我找几个来。20万刀可是140万rmb。

我估计把你杀了都卖不了这么多。

**Comment by zhaoliang0302** [comment]
> > > 万刀了再跟我比比
> > 
> > 
> > 🤣大路上比你收入高的多呢，你是不是见到高的都得
> 
> 有吗？随便给我找几个来。20万刀可是140万rmb。
> 
> 我估计把你杀了都卖不了这么多。

你要相信人外有人，口气真大，你的学历只会<=我，不知道你狂什么😅

**Comment by wizardforcel** [comment]
> > > > 万刀了再跟我比比
> > > 
> > > 
> > > 🤣大路上比你收入高的多呢，你是不是见到高的都得
> > 
> > 
> > 有吗？随便给我找几个来。20万刀可是140万rmb。
> > 我估计把你杀了都卖不了这么多。
> 
> 你要相信人外有人，口气真大，你的学历只会<=我，不知道你狂什么😅

学历有啥用，能挣钱吗？有本事上资产证明，没本事就滚蛋。

**Comment by zhaoliang0302** [comment]
> > > > > 万刀了再跟我比比
> > > > 
> > > > 
> > > > 🤣大路上比你收入高的多呢，你是不是见到高的都得
> > > 
> > > 
> > > 有吗？随便给我找几个来。20万刀可是140万rmb。
> > > 我估计把你杀了都卖不了这么多。
> > 
> > 
> > 你要相信人外有人，口气真大，你的学历只会<=我，不知道你狂什么😅
> 
> 学历有啥用，能挣钱吗？有本事上资产证明，没本事就滚蛋。

你上个看看，毕竟你装逼也需要证据吧，看看你的收入够不够你所谓的杀个人的🤣

**Comment by zhaoliang0302** [comment]
> > > > > 万刀了再跟我比比
> > > > 
> > > > 
> > > > 🤣大路上比你收入高的多呢，你是不是见到高的都得
> > > 
> > > 
> > > 有吗？随便给我找几个来。20万刀可是140万rmb。
> > > 我估计把你杀了都卖不了这么多。
> > 
> > 
> > 你要相信人外有人，口气真大，你的学历只会<=我，不知道你狂什么😅
> 
> 学历有啥用，能挣钱吗？有本事上资产证明，没本事就滚蛋。

找到你的资产证明了，出息大了😅
![Screenshot_20230821-114903](https://github.com/The-Run-Philosophy-Organization/run/assets/42333702/772ed998-212d-4c5e-8dd9-d1d596555364)

**Comment by cultivater** [comment]
> > > > 万刀了再跟我比比
> > > 
> > > 
> > > 🤣大路上比你收入高的多呢，你是不是见到高的都得
> > 
> > 
> > 有吗？随便给我找几个来。20万刀可是140万rmb。
> > 我估计把你杀了都卖不了这么多。
> 
> 你要相信人外有人，口气真大，你的学历只会<=我，不知道你狂什么😅

南京医科大学的渣渣也在这狗叫，笑死爹了

**Comment by cultivater** [comment]
也只能水水三区SCI这样的乐色了哈哈哈

**Comment by zhaoliang0302** [comment]
> 也只能水水三区SCI这样的乐色了哈哈哈

是的，我是菜鸡，请大佬给我看看你的，我也学习学习
