### ISSUE TITLE
加拿大各省省提名具体要求.md

### ISSUE THREAD

**Issue by Shonennn** [The-Run-Philosophy-Organization/run#73]
补充一个加拿大各省省提名具体要求 来源我之前在 Reddit 上的一个贴
----------------------------------------- 
**安省**

Masters Graduate stream

-EE入池（所有省提名都要EE入池的）

-至少一年全日制学习（项目上的要求即可 具体操作两年制可以提前一年半上完）

-获得来自安省院校的毕业证书

-语言成绩CLB7 雅思G类6666

-目前合法状态居住在安省

-有30000刀用于生活的资金 （这条可以用offer抵 例如拿到一个25000年薪的offer 那么你只需要有5000刀存款即可）

-有意向居住在安省

-有待在加拿大的合法状态（PGWP工签 学签等）

-毕业两年内申请

附上官网链接OINP硕士研究生流|ontario.ca

这条stream是有单独的省提名分数的 以下是具体打分项目 目前最新邀请分数是41分 老嗨们自己对号入座

-工作级别：NOC A类3分，其他类别0分； 
-加拿大工作长度：12个月以上4分； 
-去年年薪：4万加币以上：3分； 
-学科领域：工程、健康10分，数学、计算机科学9分，商科和技工类7分，社会、法律、教育和其他科学6分，其他文科5分；
- 加拿大教育经验：加拿大单学历5分，加拿大双学历10分； 
-语言：CLB 9级10分，8级6分，7级4分，7级以下不符合要求；
 -第二语言：CLB 6级10分，没有第二语言5分；
 -学习区域：大多伦多地区以外10分，大多伦多地区6分。

French-Speaking Skilled Worker stream

-EE入池(FSW或CEC)

-至少一年NOC0AB工作经验 可以是加拿大或者海外

-必须有加拿大本科或本科以上学历或者国外同等学历（国内的学历搞个ECA认证即可）

-CLB7级别的法语以及CLB6级别的英语

-有30000刀用于生活的资金 （这条可以用offer抵 例如拿到一个25000年薪的offer 那么你只需要有5000刀存款即可）

-有意向居住在安省

-有待在加拿大的合法状态（PGWP工签 学签等）

-FSWP六项打分至少67 (你要英语说得好有硕士学位的话还算好凑)
　　1、语言最高28。第一语言要求最低CLB 7级，听、说、读、写每项4分，所以最低16分。任何一科得到CLB 8级可以获得额外1分，9级额外2分。举例说明一下语言得分：若雅思说、听、读、写分别是：6、8、6.5、7，对应CLB 7级，9级，8级，9级，则得分是：4+6+5+6=21。第二语言听说读写均达到CLB 5级，可以获得额外4分，
　　2、学历最高25。博士：25分，硕士：23分，两个以上大专或本科（其中一个至少3年）22分，3年以上大专或本科:21分，2年大专:19分，1年大专:15分，高中毕业:5分。
　　3、工作经验最高15。6年或以上：15分，4-5年：13分，2-3年：11分，1年：9分。只有过去10年内的NOC 0、A或者B类的工作经验可以算分，可以是加拿大以外的工作经验，可以不连续，可以是不同的NOC类别（但至少要有一年连续的同一类别的工作经验），可以自雇，可以是在读期间的工作经历。
　　4、年龄最高12：18-35岁：12分，从35岁开始每增加1岁减1分。不满18岁或47岁（含）以上0分。
　　5、有LMIA：额外10分。
　　6、适应分最高10。配偶达到CLB 4级（雅思成绩听4.5、读3.5、写4、说4）：5分；申请人或配偶加拿大全职学习2年：5分；申请人或配偶加拿大1年工作经验：5分；有LMIA：5分；亲属：5分（公民或永久居民，住在加拿大，18岁以上）。
这条法语stream从出来之后貌似没招满过 有条件的话建议走这个 基本一年内能走完流程

**BC省**

BCPNP

EE入池

三年内在BCPNP计划院校名单中获得一下学位

农业
生物和生物医学科学
计算机和信息科学及支持服务
工程
工程技术
健康专业和相关临床科学
数学和统计学
自然资源保护与研究
物理科学
因为要求简单所以很多中介和sub里老哥都爱推荐这个

然而名单里的学校竞争都很激烈并且走流程的时间会拖得很长

官网链接： WelcomeBC / Express Entry BC – International Post-Graduate | BC, Canada

**魁北克**

PEQ工作类

-18岁以上并合法居住在魁北克

-法语达到魁北克Level7的水平

-三年内至少有两年是从事 NOC0AB类工作

-PEQ毕业生类

-18岁以上并合法居住在魁北克

-法语达到魁北克Level7的水平

-获得魁北克院校学位

-获得本、硕、博学位之一的需要有一年NOC0AB工作经验

官网链接： Conditions for Québec graduates | Gouvernement du Québec (quebec.ca)

**阿尔伯塔**

AINP EE Stream

-EE入池

-EE分数达到300分（网上自己找EE计算器吧 有加拿大学历的话很容易达到我只能说）

-有意向居住在阿省

-目前的职业是支持艾伯塔省经济发展和多样化的职业

-以下的一条或多条因素可以提高你被捞出来的概率

1.有阿省的工作机会
2.是加拿大院校的毕业生
3.父母，孩子，兄弟或姐妹是居住在阿省的永久居民，或者居住在阿省的加拿大公民
4.法语是你第一语言

**曼省**（这批地方鸟不拉屎而且华人中介浓度太高 有比较大概率进坑 除非没得选否则我其实不太推荐）

国际生Stream

-获得曼省院校硕士或博士学位并且课程时长至少一年

-必须有雇主和你签订NOC0AB职业一年的全职合同

-语言至少CLB7

-省内经验类Stream（中介卖工作的主要Stream 并且卖工作是非法的）

-曼省毕业生在紧缺职业工作6个月或者非紧缺职业工作12个月 ，不需要和所学相关。

-外省毕业生，在曼省紧缺职业工作12个月，不需要和所学相关；

-全职或长期的工作合同

-达到语言要求

1. 受监管的职业CLB7
2. 技工CLB6
3. NOC 0AB类职业 CLB5（但凡学过英语都不至于clb5都过不了）
4. NOC C D类职业 CLB4
总之这批地方能别去就别去 别听中介瞎jb吹 全都是想卖你几十万一份工作的

**萨省**（冷门的鸟不拉屎省 信息相对较少 但是要JAL信 大概率也有中介卖工作）

-工签Stream

-必须持有毕业工签PGWP（基本一年制以上毕业申请就有一到三年的工签）

-雇主提前为你申请JAL信担保（不难 但容易被中介利用信息差割韭菜）

-合法为萨省雇主工作半年

-本省毕业生这半年的工作经验没有额外的要求，不用和所学相关，不用和担保的职位相关，可以是校内、校外的工作经验，也可以是读书期间的工作经验 5.外省毕业生这半年的工作经验需要和专业相关

-没语言要求

**Comment by ouzc12358** [comment]
谢谢问下，我现在有个加拿大阿省Calgary工作的offer，年薪在70000加元左右，做仪器仪表相关工作，这样润的话有啥条件
英文我基本可以但还没考雅思，长期做海外工作但base上海




Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Shonennn ***@***.***>
Sent: Friday, April 15, 2022 10:19:05 AM
To: The-Run-Philosophy-Organization/run ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [The-Run-Philosophy-Organization/run] 加拿大各省省提名具体要求.md (Issue #73)


补充一个加拿大各省省提名具体要求 来源我之前在 Reddit 上的一个贴

安省

Masters Graduate stream

-EE入池（所有省提名都要EE入池的）

-至少一年全日制学习（项目上的要求即可 具体操作两年制可以提前一年半上完）

-获得来自安省院校的毕业证书

-语言成绩CLB7 雅思G类6666

-目前合法状态居住在安省

-有30000刀用于生活的资金 （这条可以用offer抵 例如拿到一个25000年薪的offer 那么你只需要有5000刀存款即可）

-有意向居住在安省

-有待在加拿大的合法状态（PGWP工签 学签等）

-毕业两年内申请

附上官网链接OINP硕士研究生流|ontario.ca

这条stream是有单独的省提名分数的 以下是具体打分项目 目前最新邀请分数是41分 老嗨们自己对号入座

-工作级别：NOC A类3分，其他类别0分；
-加拿大工作长度：12个月以上4分；
-去年年薪：4万加币以上：3分；
-学科领域：工程、健康10分，数学、计算机科学9分，商科和技工类7分，社会、法律、教育和其他科学6分，其他文科5分；

  *   加拿大教育经验：加拿大单学历5分，加拿大双学历10分；
-语言：CLB 9级10分，8级6分，7级4分，7级以下不符合要求；
-第二语言：CLB 6级10分，没有第二语言5分；
-学习区域：大多伦多地区以外10分，大多伦多地区6分。

French-Speaking Skilled Worker stream

-EE入池(FSW或CEC)

-至少一年NOC0AB工作经验 可以是加拿大或者海外

-必须有加拿大本科或本科以上学历或者国外同等学历（国内的学历搞个ECA认证即可）

-CLB7级别的法语以及CLB6级别的英语

-有30000刀用于生活的资金 （这条可以用offer抵 例如拿到一个25000年薪的offer 那么你只需要有5000刀存款即可）

-有意向居住在安省

-有待在加拿大的合法状态（PGWP工签 学签等）

-FSWP六项打分至少67 (你要英语说得好有硕士学位的话还算好凑)
　　1、语言最高28。第一语言要求最低CLB 7级，听、说、读、写每项4分，所以最低16分。任何一科得到CLB 8级可以获得额外1分，9级额外2分。举例说明一下语言得分：若雅思说、听、读、写分别是：6、8、6.5、7，对应CLB 7级，9级，8级，9级，则得分是：4+6+5+6=21。第二语言听说读写均达到CLB 5级，可以获得额外4分，
　　2、学历最高25。博士：25分，硕士：23分，两个以上大专或本科（其中一个至少3年）22分，3年以上大专或本科:21分，2年大专:19分，1年大专:15分，高中毕业:5分。
　　3、工作经验最高15。6年或以上：15分，4-5年：13分，2-3年：11分，1年：9分。只有过去10年内的NOC 0、A或者B类的工作经验可以算分，可以是加拿大以外的工作经验，可以不连续，可以是不同的NOC类别（但至少要有一年连续的同一类别的工作经验），可以自雇，可以是在读期间的工作经历。
　　4、年龄最高12：18-35岁：12分，从35岁开始每增加1岁减1分。不满18岁或47岁（含）以上0分。
　　5、有LMIA：额外10分。
　　6、适应分最高10。配偶达到CLB 4级（雅思成绩听4.5、读3.5、写4、说4）：5分；申请人或配偶加拿大全职学习2年：5分；申请人或配偶加拿大1年工作经验：5分；有LMIA：5分；亲属：5分（公民或永久居民，住在加拿大，18岁以上）。
这条法语stream从出来之后貌似没招满过 有条件的话建议走这个 基本一年内能走完流程

BC省

BCPNP

EE入池

三年内在BCPNP计划院校名单中获得一下学位

农业
生物和生物医学科学
计算机和信息科学及支持服务
工程
工程技术
健康专业和相关临床科学
数学和统计学
自然资源保护与研究
物理科学
因为要求简单所以很多中介和sub里老哥都爱推荐这个

然而名单里的学校竞争都很激烈并且走流程的时间会拖得很长

官网链接： WelcomeBC / Express Entry BC C International Post-Graduate | BC, Canada

魁北克

PEQ工作类

-18岁以上并合法居住在魁北克

-法语达到魁北克Level7的水平

-三年内至少有两年是从事 NOC0AB类工作

-PEQ毕业生类

-18岁以上并合法居住在魁北克

-法语达到魁北克Level7的水平

-获得魁北克院校学位

-获得本、硕、博学位之一的需要有一年NOC0AB工作经验

官网链接： Conditions for Québec graduates | Gouvernement du Québec (quebec.ca)

阿尔伯塔

AINP EE Stream

-EE入池

-EE分数达到300分（网上自己找EE计算器吧 有加拿大学历的话很容易达到我只能说）

-有意向居住在阿省

-目前的职业是支持艾伯塔省经济发展和多样化的职业

-以下的一条或多条因素可以提高你被捞出来的概率

1.有阿省的工作机会
2.是加拿大院校的毕业生
3.父母，孩子，兄弟或姐妹是居住在阿省的永久居民，或者居住在阿省的加拿大公民
4.法语是你第一语言

曼省（这批地方鸟不拉屎而且华人中介浓度太高 有比较大概率进坑 除非没得选否则我其实不太推荐）

国际生Stream

-获得曼省院校硕士或博士学位并且课程时长至少一年

-必须有雇主和你签订NOC0AB职业一年的全职合同

-语言至少CLB7

-省内经验类Stream（中介卖工作的主要Stream 并且卖工作是非法的）

-曼省毕业生在紧缺职业工作6个月或者非紧缺职业工作12个月 ，不需要和所学相关。

-外省毕业生，在曼省紧缺职业工作12个月，不需要和所学相关；

-全职或长期的工作合同

-达到语言要求

  1.  受监管的职业CLB7
  2.  技工CLB6
  3.  NOC 0AB类职业 CLB5（但凡学过英语都不至于clb5都过不了）
  4.  NOC C D类职业 CLB4
总之这批地方能别去就别去 别听中介瞎jb吹 全都是想卖你几十万一份工作的

萨省（冷门的鸟不拉屎省 信息相对较少 但是要JAL信 大概率也有中介卖工作）

-工签Stream

-必须持有毕业工签PGWP（基本一年制以上毕业申请就有一到三年的工签）

-雇主提前为你申请JAL信担保（不难 但容易被中介利用信息差割韭菜）

-合法为萨省雇主工作半年

-本省毕业生这半年的工作经验没有额外的要求，不用和所学相关，不用和担保的职位相关，可以是校内、校外的工作经验，也可以是读书期间的工作经验 5.外省毕业生这半年的工作经验需要和专业相关

-没语言要求

―

**Comment by Shonennn** [comment]
> 

先出去再说吧 你可以看看阿省官网 
像阿省这种草原省一般都很好留的 卡尔加里现在在加拿大的性价比很高

**Comment by the-run-philosophy** [comment]
转换成pr

**Comment by the-run-philosophy** [comment]
已转换成md文档录入
