### ISSUE TITLE
希望能补充美利坚合众国“误炸”逝者名单

### ISSUE THREAD

**Issue by willisdai** [The-Run-Philosophy-Organization/run#75]

**Comment by sgfcz** [comment]
这是开源的吧。。。。你自己往上推一下不行？

**Comment by 78qw5ojhj** [comment]
![image](https://user-images.githubusercontent.com/103625387/163509814-7537d6bf-f71d-45fa-af6f-d7ebbb65726d.png)

**Comment by 78qw5ojhj** [comment]
@1011cat 扣一送数一数二的兔女郎🥵

**Comment by lengfengwujing** [comment]
请学好英语，使用Google搜索各大新闻网站

**Comment by Dunky-Z** [comment]
> ![image](https://user-images.githubusercontent.com/103625387/163509814-7537d6bf-f71d-45fa-af6f-d7ebbb65726d.png)

能解释下前因后果吗？1450。放个照片想带节奏？超级毒王，不服从防疫政策

**Comment by 78qw5ojhj** [comment]
> > ![image](https://user-images.githubusercontent.com/103625387/163509814-7537d6bf-f71d-45fa-af6f-d7ebbb65726d.png)
> 
> 能解释下前因后果吗？1450。放个照片想带节奏？超级毒王，不服从防疫政策

如果老人是因为不会使用手机需要外出购买生活用品呢，就和你一样在GitHub上搜索学习强国脚本，爱国也能一键完成的么？我都是怀着感恩的心24k纯手工完成的鸭！开发这些挂的人和他们的用户一定都是狗罕见吧🤮
![image](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiu-xuicpH7HoeVtBrhn-5k5e82hzz-xTd7Q&usqp=CAU)
