### ISSUE TITLE
说白了，有钱就等于拥有自由，不会真的有人觉得只要出了国就自由了吧

### ISSUE THREAD

**Issue by UyyUtt** [The-Run-Philosophy-Organization/run#76]

**Comment by 78qw5ojhj** [comment]
[你说的很对，但谷爱凌说只有不自信的人才去嘲笑别人，美国这种行为无疑是搬起石头砸自己的脚，据约翰霍布金斯大学统计美国昨日新增疫情患者破百万，谷爱凌表示一天要睡够十个小时，而冰墩墩仍供不应求](https://youtube.com/shorts/qLIbbElmGGE?feature=share)

**Comment by 78qw5ojhj** [comment]
@zhanyeye 詹晔晔，已在12377举办，，，

**Comment by zhanyeye** [comment]
> @zhanyeye 詹晔晔，已在12377举办，，，

有毛病

**Comment by fcpglss** [comment]
有钱也不一定自由,比如马云,王健林.但是我的偶像谷爱凌就很自由.他们区别就在于谷爱凌在美国的时候是美国人,在中国是中国人.而马云,王健林只能是中国人.可见润的重要性

**Comment by 78qw5ojhj** [comment]
> > @zhanyeye 詹晔晔，已在12377举办，，，
> 
> 有毛病

![image](https://user-images.githubusercontent.com/103625387/163515518-67a93449-523e-463b-8c30-867bf80bfc72.png)

**Comment by zhanyeye** [comment]
> > > @zhanyeye 詹晔晔，已在12377举办，，，
> > 
> > 
> > 有毛病
> 
> ![image](https://user-images.githubusercontent.com/103625387/163515809-2ab64238-cc85-4840-88d6-dc9f2752611a.png) ![image](https://user-images.githubusercontent.com/103625387/163515518-67a93449-523e-463b-8c30-867bf80bfc72.png)

22小时前创建的号，你也好意思来这发言，你去豆瓣，微博，知乎，好不好。污染环境。
![image](https://user-images.githubusercontent.com/35565811/163516240-9a876fdc-1e69-43b6-91b5-5e847a9a6fd7.png)

**Comment by 78qw5ojhj** [comment]
> > > > @zhanyeye 詹晔晔，已在12377举办，，，
> > > 
> > > 
> > > 有毛病
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/103625387/163515809-2ab64238-cc85-4840-88d6-dc9f2752611a.png) ![image](https://user-images.githubusercontent.com/103625387/163515518-67a93449-523e-463b-8c30-867bf80bfc72.png)
> 
> 22小时前创建的号，你也好意思来这发言，你去豆瓣，微博，知乎，好不好。污染环境。 ![image](https://user-images.githubusercontent.com/35565811/163516240-9a876fdc-1e69-43b6-91b5-5e847a9a6fd7.png)

詹大佐，github又不是不允许用匿名账号发言，你不喜欢也可以用匿名账号亲自查看，亲自点踩，既然你实名制上网我为什么不能说呢lol

**Comment by ouzc12358** [comment]
在墙内还没明白权远大于钱这点那说明你挺天真的

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: 于鑫月 ***@***.***>
Sent: Friday, April 15, 2022 10:26:39 AM
To: The-Run-Philosophy-Organization/run ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [The-Run-Philosophy-Organization/run] 说白了，有钱就等于拥有自由，不会真的有人觉得只要出了国就自由了吧 (Issue #76)


―
