### ISSUE TITLE
理性看待Run

### ISSUE THREAD

**Issue by jackluson** [The-Run-Philosophy-Organization/run#78]
大多数华人run到国外了融不进去国外的生活, 还面临各种歧视, 看不起问题 , 只能选择一种卑微的姿态生活。 社会主义和资本主义选择站队哪一个， 需要理性分析， 辩证看待。
但是我看不起某种人就是run到国外之后，就一味的舔国外, 同时又拼命的踩国内。选择性的报告国内阴暗的一面， 忽视国外阴暗的一面。这样做是什么意思的。再怎么说祖国也是培养你长大的。 现在你run出来了， 你不给祖国回报就算了，还添乱， 这是什么心思。在国外被欺负了， 在国内找存在感，优越感？

**Comment by ouzc12358** [comment]
又有人代表了大多数了。所以叫布尔什维克。

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: camel-lu ***@***.***>
Sent: Friday, April 15, 2022 10:54:24 AM
To: The-Run-Philosophy-Organization/run ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [The-Run-Philosophy-Organization/run] 理性看待Run (Issue #78)


大多数华人run到国外了融不进去国外的生活, 还面临各种歧视, 看不起问题 , 只能选择一种卑微的姿态生活。 社会主义和资本主义选择站队哪一个， 需要理性分析， 辩证看待。
但是我看不起某种人就是run到国外之后，就一味的舔国外, 同时又拼命的踩国内。选择性的报告国内阴暗的一面， 忽视国外阴暗的一面。这样做是什么意思的。再怎么说祖国也是培养你长大的。 现在你run出来了， 你不给祖国回报就算了，还添乱， 这是什么心思。在国外被欺负了， 在国内找存在感，优越感？

―

**Comment by 78qw5ojhj** [comment]
听我说👂👂👂谢谢你🙏🙏🙏因为有你👉👉👉温暖了四季🌈🌈🌈谢谢你🙏🙏🙏感谢有你👉👉👉世界更美丽🌏🌏🌏我要谢谢你🙏🙏🙏因为有你👉👉👉爱常在心底💃💃💃
![image](https://user-images.githubusercontent.com/103625387/163511544-2805b1d1-8be2-4eb9-84f2-74bd23338cc5.png)

**Comment by sgfcz** [comment]
你这一大段，跟理性毫无关系。。。。。
添乱都出来了，赶紧爬吧
先是人才有家，其次才有国
而不是寻思着不给老爷添麻烦

**Comment by a186r** [comment]
小粉红，给爷爬

**Comment by CarlBentham** [comment]
操你妈的又是这种言论，我在爱尔兰呆了三年见过的种族歧视屈指可数，在国内读研那会我跟的导师是个黑人，挺有学问的，但是走在路上天天都能被他妈的调侃，怎么国内种族歧视不严重？说着是什么大学给黑人配学伴，实际上你妈比一个个看不起印度人看不起韩国人看不起日本人看不起非洲人，天天宣传你妈比的融入不进去生活，因为你他妈的杂种一个根本不配融入文明社会，傻逼。

**Comment by lengfengwujing** [comment]
你说错了，是**半封建半权贵官僚化的资本主义** 和 资本主义选择站队， 确实应该慎重考虑

**Comment by jackluson** [comment]
issues 已经被关闭，最后一次回答。 评论区果然如此，充满戾气。 无可置疑，有些人在国外生活的很好，那我祝福你。但是别忘了，那是你的努力的结果。精英阶层在哪个社会都能享受很好的待遇。但排华，歧视华人这种现象在欧美是不争的事实。恰如评论区里面说到国内也有一大批人歧视国外人一样。排华原因是多元复杂的， 比如华人挤压国外人的生活空间， 还有就是华人一直以来在国外的地位就是卑微的。白人眼中的中国就是落后，愚钝的。还有一部分华人run出来之后。选择性报告中国不好的一面。 恰好印证了一些白人固化的想法。 那不歧视你歧视谁呢?
理性分析run不是空想出来的， 可以尝试性去国外一段时间，结合一些移民专家，亲朋好友的意见做出自己的决定

> 大多数华人run到国外了融不进去国外的生活, 还面临各种歧视, 看不起问题 , 只能选择一种卑微的姿态生活。 社会主义和资本主义选择站队哪一个， 需要理性分析， 辩证看待。 但是我看不起某种人就是run到国外之后，就一味的舔国外, 同时又拼命的踩国内。选择性的报告国内阴暗的一面， 忽视国外阴暗的一面。这样做是什么意思的。再怎么说祖国也是培养你长大的。 现在你run出来了， 你不给祖国回报就算了，还添乱， 这是什么心思。在国外被欺负了， 在国内找存在感，优越感？
