### ISSUE TITLE
自由是什么?

### ISSUE THREAD

**Issue by kaizhang0124** [The-Run-Philosophy-Organization/run#81]
自由不是你想怎么做就怎么做. 自由是有限定了. 如果任由按照个人意愿做事, 只会使得这个社会更加糟糕.

说一句: 现在的中国已经不是你脑子里想象的样子, 你再怎么贬低他也会影响他日益强大.

**Comment by CarlBentham** [comment]
说实话是为了贬低，指出错误是为了贬低，讲道理是为了影响它日益强大，我可去你妈的。

**Comment by cheng-bai** [comment]
强大的人不惧别人的贬低,意味的让别人不说话反倒证明自己纸老虎.

**Comment by 78qw5ojhj** [comment]
`你再怎么贬低他也会影响他日益强大.`
英雄联盟！非常好评论，社会学分加+1,000,000，爱来自瓷器👍
![image](https://user-images.githubusercontent.com/103625387/163516435-2d5067f4-19f6-4397-bcb1-dc6dc2c0fe59.png)

**Comment by the-run-philosophy** [comment]
讨论不要提issue，请提交pr或去讨论区
