### ISSUE TITLE
民主是什么？是`你要为我做主`吗？引用《遥远的救世主》里的一句话

### ISSUE THREAD

**Issue by yunzhaoyu2050** [The-Run-Philosophy-Organization/run#85]
##### 民主是什么？是`你要为我做主`吗？引用《遥远的救世主》里的一句话“共产党也难哪现在有人动不动就拿民主开方子，以为一民主中国就万事大吉了有这么简单吗？真要是这么简单，我不认为共产党缺乏那样的胸襟，我也不认为一个政党就能阻止社会发展的趋势。忠孝文化几千年了，不是谁栽一棵民主的树就开花结果了”

**Comment by the-run-philosophy** [comment]
讨论不要提issue，请去讨论区
