### ISSUE TITLE
Should have a job interview guidance below 润学方法论/各国选择/ or 润学实例

### ISSUE THREAD

**Issue by mooxiu** [The-Run-Philosophy-Organization/run#9]
Reason:
- companies in different countries can have their own preferences
- how to prepare questions like `why do you want to come to our county?`, should I tell the truth?
-

**Comment by forrestbao** [comment]
then fork and PR

**Comment by mooxiu** [comment]
> then fork and PR

haven't run yet, expect to see success experience. Will collect some info to open a pr though.
