### ISSUE TITLE
贱不贱啊？丑国疫情死了100多万你怎么不记录一下啊？这才死几个就受不了了？

### ISSUE THREAD

**Issue by Proletarier** [The-Run-Philosophy-Organization/run#90]
不是一直吵着要共存吗？才死几个人就受不了了？

**Comment by sgfcz** [comment]
分得清人祸天灾嘛。。。。。
够傻逼的

**Comment by Zelaren** [comment]
不管我受不受得了，你受得了就行

**Comment by woshilajilao** [comment]
> 分得清人祸天灾嘛。。。。。
> 够傻逼的

说的国外那些就真的只是天灾一样…… 起码兔子还想办法抢救一下

**Comment by iamazy** [comment]
> 不是一直吵着要共存吗？才死几个人就受不了了？

虽然我和你同一立场，但咱们不能互相比烂是不是，上海的疫情真的有打破我的心理防线

**Comment by HimenoSenaa** [comment]
你不会觉得大家想润只是因为疫情吧？

**Comment by Proletarier** [comment]
> 分得清人祸天灾嘛。。。。。 够傻逼的

对对，你美爹死100多万全是天灾

**Comment by cychan2047** [comment]
公民，请勿登录GitHub这种美国境外势力网站！请回到观察者网了解最公正的事实！

**Comment by sgfcz** [comment]
> > 分得清人祸天灾嘛。。。。。
> > 够傻逼的
> 
> 说的国外那些就真的只是天灾一样…… 起码兔子还想办法抢救一下

就题目讨论，你要想讨论这个，可以开个讨论贴，慢慢讨论

**Comment by sgfcz** [comment]
> > 分得清人祸天灾嘛。。。。。 够傻逼的
> 
> 对对，你美爹死100多万全是天灾

他们自己选择死了，管我吊事。。。。你不会觉得我会可怜美国佬吧

**Comment by 4fdfdfd** [comment]
> 不是一直吵着要共存吗？才死几个人就受不了了？


看看上海张江那些被从房子里赶出来的普通百姓吧，那些跪在地方向当权者痛哭的人民，他们做错了什么？上头一句话，就要被赶出家门，只有铁拳砸到你头上时，你才不会再关心美国人死了多少，你才会关心真正生活在这个国家的人民。

**Comment by kilvn** [comment]
一群傻子围着一个垃圾堆，恶臭污染github
