### ISSUE TITLE
美国佬给了你多少资金支持这个项目？我党给你10倍去咬美国佬！

### ISSUE THREAD

**Issue by jett2020** [The-Run-Philosophy-Organization/run#91]
美国佬给了你多少资金支持这个项目？我党给你10倍去咬美国佬！

**Comment by ouzc12358** [comment]
你党？你也配姓赵？

**Comment by jett2020** [comment]
@ouzc12358 你也配当狗？

**Comment by ouzc12358** [comment]
那肯定没你配，我是人啊。


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jett2020** [comment]
@ouzc12358 狗开始咬人了

**Comment by ouzc12358** [comment]
我现拉一坨屎给你吃，别乱咬人了，饿了就说话，别乱咬人

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
