### ISSUE TITLE
技术网站整这些不相干玩意，真无语。有的是地方放，来这显眼

### ISSUE THREAD

**Issue by mytianya** [The-Run-Philosophy-Organization/run#94]

**Comment by 1211ciel** [comment]
赞同，不要把github给搞禁了。。

**Comment by Bian-Sh** [comment]
技术网站扯什么 布尔什维克 ，上升到政治层面我觉得不合适。

**Comment by pifeifei** [comment]
这是个什么 东西？ 没看懂，看前面有点 fa lun gng 的嫌疑

**Comment by lwd-temp** [comment]
> 这是个什么 东西？ 没看懂，看前面有点 fa lun gng 的嫌疑

不像，可以当作玩笑，也可以学习一下（虽然目前没什么值得注意的）。

这东西不违反GitHub的使用守则，只凭自己的好恶去认为这里不应该放这个是不可能通过举报的。
